/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  SvgInputReference,
  SvgInputReference$Outbound,
  SvgInputReference$outboundSchema,
} from "./svginputreference.js";

/**
 * Reasoning effort applied to this animation. When omitted, Arrow uses its default.
 */
export const ReasoningEffort = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Xhigh: "xhigh",
} as const;
/**
 * Reasoning effort applied to this animation. When omitted, Arrow uses its default.
 */
export type ReasoningEffort = ClosedEnum<typeof ReasoningEffort>;

export type AnimateSVGRequest = {
  /**
   * Upper bound for output token count.
   */
  maxOutputTokens?: number | undefined;
  /**
   * Model identifier to use for animation.
   */
  model: string;
  /**
   * Optional animation prompt. If omitted, the model chooses a suitable animation.
   */
  prompt?: string | undefined;
  /**
   * Reasoning effort applied to this animation. When omitted, Arrow uses its default.
   */
  reasoningEffort?: ReasoningEffort | undefined;
  /**
   * When true, emits a Server-Sent Events stream.
   */
  stream?: boolean | undefined;
  /**
   * Remote or base64-encoded SVG source to animate.
   */
  svgSource: SvgInputReference;
  /**
   * Animation sampling temperature.
   */
  temperature?: number | undefined;
};

/** @internal */
export const ReasoningEffort$outboundSchema: z.ZodNativeEnum<
  typeof ReasoningEffort
> = z.nativeEnum(ReasoningEffort);

/** @internal */
export type AnimateSVGRequest$Outbound = {
  max_output_tokens?: number | undefined;
  model: string;
  prompt?: string | undefined;
  reasoning_effort?: string | undefined;
  stream: boolean;
  svg_source: SvgInputReference$Outbound;
  temperature: number;
};

/** @internal */
export const AnimateSVGRequest$outboundSchema: z.ZodType<
  AnimateSVGRequest$Outbound,
  z.ZodTypeDef,
  AnimateSVGRequest
> = z.object({
  maxOutputTokens: z.number().int().optional(),
  model: z.string(),
  prompt: z.string().optional(),
  reasoningEffort: ReasoningEffort$outboundSchema.optional(),
  stream: z.boolean().default(false),
  svgSource: SvgInputReference$outboundSchema,
  temperature: z.number().default(1),
}).transform((v) => {
  return remap$(v, {
    maxOutputTokens: "max_output_tokens",
    reasoningEffort: "reasoning_effort",
    svgSource: "svg_source",
  });
});

export function animateSVGRequestToJSON(
  animateSVGRequest: AnimateSVGRequest,
): string {
  return JSON.stringify(
    AnimateSVGRequest$outboundSchema.parse(animateSVGRequest),
  );
}
