/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const MimeType = {
  ImageSvgPlusXml: "image/svg+xml",
} as const;
export type MimeType = ClosedEnum<typeof MimeType>;

export type AnimatedSvgResponse = {
  /**
   * Loop period for the generated animation in milliseconds.
   */
  loopPeriodMs?: number | null | undefined;
  mimeType: MimeType;
  /**
   * Opening animation duration in milliseconds.
   */
  openingAnimationMs?: number | null | undefined;
  svg: string;
};

/** @internal */
export const MimeType$inboundSchema: z.ZodNativeEnum<typeof MimeType> = z
  .nativeEnum(MimeType);

/** @internal */
export const AnimatedSvgResponse$inboundSchema: z.ZodType<
  AnimatedSvgResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  loop_period_ms: z.nullable(z.number().int()).optional(),
  mime_type: MimeType$inboundSchema,
  opening_animation_ms: z.nullable(z.number().int()).optional(),
  svg: z.string(),
}).transform((v) => {
  return remap$(v, {
    "loop_period_ms": "loopPeriodMs",
    "mime_type": "mimeType",
    "opening_animation_ms": "openingAnimationMs",
  });
});

export function animatedSvgResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnimatedSvgResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnimatedSvgResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnimatedSvgResponse' from JSON`,
  );
}
