/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Not Implemented
 */
export type AnimateSVGRequest = {};

/** @internal */
export type AnimateSVGRequest$Outbound = {};

/** @internal */
export const AnimateSVGRequest$outboundSchema: z.ZodType<
  AnimateSVGRequest$Outbound,
  z.ZodTypeDef,
  AnimateSVGRequest
> = z.object({});

export function animateSVGRequestToJSON(
  animateSVGRequest: AnimateSVGRequest,
): string {
  return JSON.stringify(
    AnimateSVGRequest$outboundSchema.parse(animateSVGRequest),
  );
}
