/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Aspect ratio constraint for the generated SVG, specified as "width:height".
 *
 * @remarks
 * - `1:1`: Square
 * - `4:3`: Standard/classic
 * - `3:4`: Portrait standard
 * - `16:9`: Landscape/widescreen
 * - `9:16`: Portrait/tall (mobile)
 * - `3:2`: Photo landscape
 * - `2:3`: Photo portrait
 * - `21:9`: Ultra-wide/cinematic
 */
export const AspectRatio = {
  Eleven: "1:1",
  FortyThree: "4:3",
  ThirtyFour: "3:4",
  OneHundredAndSixtyNine: "16:9",
  NineHundredAndSixteen: "9:16",
  ThirtyTwo: "3:2",
  TwentyThree: "2:3",
  TwoHundredAndNineteen: "21:9",
} as const;
/**
 * Aspect ratio constraint for the generated SVG, specified as "width:height".
 *
 * @remarks
 * - `1:1`: Square
 * - `4:3`: Standard/classic
 * - `3:4`: Portrait standard
 * - `16:9`: Landscape/widescreen
 * - `9:16`: Portrait/tall (mobile)
 * - `3:2`: Photo landscape
 * - `2:3`: Photo portrait
 * - `21:9`: Ultra-wide/cinematic
 */
export type AspectRatio = ClosedEnum<typeof AspectRatio>;

/** @internal */
export const AspectRatio$outboundSchema: z.ZodNativeEnum<typeof AspectRatio> = z
  .nativeEnum(AspectRatio);
