/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { AspectRatio, AspectRatio$outboundSchema } from "./aspectratio.js";
import {
  SafeZone,
  SafeZone$Outbound,
  SafeZone$outboundSchema,
} from "./safezone.js";
import {
  ViewBox,
  ViewBox$Outbound,
  ViewBox$outboundSchema,
} from "./viewbox.js";

/**
 * Controls the coordinate system and "Safe Zones" to prevent clipping/bad cropping.
 *
 * @remarks
 * NOTE: "mode" determines the default canvas if this is omitted.
 */
export type Canvas = {
  /**
   * Aspect ratio constraint for the generated SVG, specified as "width:height".
   *
   * @remarks
   * - `1:1`: Square
   * - `4:3`: Standard/classic
   * - `3:4`: Portrait standard
   * - `16:9`: Landscape/widescreen
   * - `9:16`: Portrait/tall (mobile)
   * - `3:2`: Photo landscape
   * - `2:3`: Photo portrait
   * - `21:9`: Ultra-wide/cinematic
   */
  aspectRatio?: AspectRatio | undefined;
  /**
   * The "Safe Zone" is the guaranteed empty margin between content and edge.
   *
   * @remarks
   * Prevents clipping and bad cropping.
   */
  safeZone?: SafeZone | undefined;
  /**
   * ViewBox dimensions for the SVG coordinate system
   */
  viewBox?: ViewBox | undefined;
};

/** @internal */
export type Canvas$Outbound = {
  aspect_ratio: string;
  safe_zone?: SafeZone$Outbound | undefined;
  view_box?: ViewBox$Outbound | undefined;
};

/** @internal */
export const Canvas$outboundSchema: z.ZodType<
  Canvas$Outbound,
  z.ZodTypeDef,
  Canvas
> = z.object({
  aspectRatio: AspectRatio$outboundSchema.default("1:1"),
  safeZone: SafeZone$outboundSchema.optional(),
  viewBox: ViewBox$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    aspectRatio: "aspect_ratio",
    safeZone: "safe_zone",
    viewBox: "view_box",
  });
});

export function canvasToJSON(canvas: Canvas): string {
  return JSON.stringify(Canvas$outboundSchema.parse(canvas));
}
