/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SVGDocument, SVGDocument$inboundSchema } from "./svgdocument.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type CollectionResponse = {
  /**
   * Unix timestamp of when the response was created
   */
  created: number;
  /**
   * Array of generated SVG documents in the collection
   */
  items: Array<SVGDocument>;
  usage?: Usage | undefined;
};

/** @internal */
export const CollectionResponse$inboundSchema: z.ZodType<
  CollectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.number().int(),
  items: z.array(SVGDocument$inboundSchema),
  usage: Usage$inboundSchema.optional(),
});

export function collectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CollectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CollectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CollectionResponse' from JSON`,
  );
}
