/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  ColorAdherence,
  ColorAdherence$outboundSchema,
} from "./coloradherence.js";
import {
  ColorRoles,
  ColorRoles$Outbound,
  ColorRoles$outboundSchema,
} from "./colorroles.js";

/**
 * The color system configuration for SVG generation
 */
export type Colors = {
  /**
   * How strictly the model must adhere to the provided colors.
   *
   * @remarks
   * - `strict`: Only use exact hex codes provided
   * - `tints_and_shades`: Can adjust lightness/opacity, but no new hues
   * - `creative`: Palette is a suggestion/starting point
   */
  adherence?: ColorAdherence | undefined;
  /**
   * Whether to allow opacity/transparency variations
   */
  allowOpacity?: boolean | undefined;
  /**
   * Soft limit on unique colors
   */
  maxColors?: number | undefined;
  /**
   * General list of allowed colors (hex codes)
   */
  palette?: Array<string> | undefined;
  /**
   * Semantic mapping of colors to specific roles
   */
  roles?: ColorRoles | undefined;
  /**
   * If true, allows <linearGradient> and <radialGradient> definitions
   */
  useGradients?: boolean | undefined;
};

/** @internal */
export type Colors$Outbound = {
  adherence: string;
  allow_opacity: boolean;
  max_colors: number;
  palette?: Array<string> | undefined;
  roles?: ColorRoles$Outbound | undefined;
  use_gradients: boolean;
};

/** @internal */
export const Colors$outboundSchema: z.ZodType<
  Colors$Outbound,
  z.ZodTypeDef,
  Colors
> = z.object({
  adherence: ColorAdherence$outboundSchema.default("tints_and_shades"),
  allowOpacity: z.boolean().default(true),
  maxColors: z.number().int().default(4),
  palette: z.array(z.string()).optional(),
  roles: ColorRoles$outboundSchema.optional(),
  useGradients: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    allowOpacity: "allow_opacity",
    maxColors: "max_colors",
    useGradients: "use_gradients",
  });
});

export function colorsToJSON(colors: Colors): string {
  return JSON.stringify(Colors$outboundSchema.parse(colors));
}
