/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * How strictly the model must adhere to the provided colors.
 *
 * @remarks
 * - `strict`: Only use exact hex codes provided
 * - `tints_and_shades`: Can adjust lightness/opacity, but no new hues
 * - `creative`: Palette is a suggestion/starting point
 */
export const ColorAdherence = {
  Strict: "strict",
  TintsAndShades: "tints_and_shades",
  Creative: "creative",
} as const;
/**
 * How strictly the model must adhere to the provided colors.
 *
 * @remarks
 * - `strict`: Only use exact hex codes provided
 * - `tints_and_shades`: Can adjust lightness/opacity, but no new hues
 * - `creative`: Palette is a suggestion/starting point
 */
export type ColorAdherence = ClosedEnum<typeof ColorAdherence>;

/** @internal */
export const ColorAdherence$outboundSchema: z.ZodNativeEnum<
  typeof ColorAdherence
> = z.nativeEnum(ColorAdherence);
