/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Semantic mapping of colors to specific roles
 */
export type ColorRoles = {
  /**
   * Accent colors for highlights and emphasis
   */
  accent?: Array<string> | undefined;
  /**
   * Colors allowed for background elements
   */
  background?: Array<string> | undefined;
  /**
   * Arbitrary custom role colors
   */
  metadata?: Array<string> | undefined;
  /**
   * Primary/main colors for key elements
   */
  primary?: Array<string> | undefined;
};

/** @internal */
export type ColorRoles$Outbound = {
  accent?: Array<string> | undefined;
  background?: Array<string> | undefined;
  metadata?: Array<string> | undefined;
  primary?: Array<string> | undefined;
};

/** @internal */
export const ColorRoles$outboundSchema: z.ZodType<
  ColorRoles$Outbound,
  z.ZodTypeDef,
  ColorRoles
> = z.object({
  accent: z.array(z.string()).optional(),
  background: z.array(z.string()).optional(),
  metadata: z.array(z.string()).optional(),
  primary: z.array(z.string()).optional(),
});

export function colorRolesToJSON(colorRoles: ColorRoles): string {
  return JSON.stringify(ColorRoles$outboundSchema.parse(colorRoles));
}
