/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

/**
 * Limits and constraints for the generated SVG output
 */
export type Constraints = {
  /**
   * Maximum total number of SVG elements
   */
  maxElements?: number | undefined;
  /**
   * Maximum number of path elements in the SVG
   */
  maxPaths?: number | undefined;
  /**
   * Maximum number of points/commands per path
   */
  maxPointsPerPath?: number | undefined;
};

/** @internal */
export type Constraints$Outbound = {
  max_elements?: number | undefined;
  max_paths?: number | undefined;
  max_points_per_path?: number | undefined;
};

/** @internal */
export const Constraints$outboundSchema: z.ZodType<
  Constraints$Outbound,
  z.ZodTypeDef,
  Constraints
> = z.object({
  maxElements: z.number().int().optional(),
  maxPaths: z.number().int().optional(),
  maxPointsPerPath: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    maxElements: "max_elements",
    maxPaths: "max_paths",
    maxPointsPerPath: "max_points_per_path",
  });
});

export function constraintsToJSON(constraints: Constraints): string {
  return JSON.stringify(Constraints$outboundSchema.parse(constraints));
}
