/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { Colors, Colors$Outbound, Colors$outboundSchema } from "./colors.js";
import { FillRule, FillRule$outboundSchema } from "./fillrule.js";
import {
  StrokeLineCap,
  StrokeLineCap$outboundSchema,
} from "./strokelinecap.js";
import {
  StrokeLineJoin,
  StrokeLineJoin$outboundSchema,
} from "./strokelinejoin.js";
import { StylePreset, StylePreset$outboundSchema } from "./stylepreset.js";

/**
 * Controls how the model applies aesthetics to the generated SVG
 */
export type Design = {
  /**
   * The color system configuration for SVG generation
   */
  colors?: Colors | undefined;
  /**
   * Detail level from 1-4:
   *
   * @remarks
   * - 1: Minimal, simple shapes
   * - 2: Standard, balanced detail
   * - 3: Detailed, more intricate
   * - 4: Highly detailed, maximum complexity
   */
  complexity?: number | undefined;
  /**
   * Algorithm for determining inside/outside of complex paths.
   *
   * @remarks
   * - `nonzero`: Standard fill rule
   * - `evenodd`: Alternating fill based on path crossings
   */
  fillRule?: FillRule | undefined;
  /**
   * If true, generates a filled <rect> background layer
   */
  includeBackground?: boolean | undefined;
  /**
   * The shape at the end of open paths.
   *
   * @remarks
   * - `butt`: Flat edge at the exact endpoint
   * - `round`: Rounded edge extending past endpoint
   * - `square`: Square edge extending past endpoint
   */
  linecap?: StrokeLineCap | undefined;
  /**
   * The shape at the corners where paths meet.
   *
   * @remarks
   * - `miter`: Sharp pointed corner
   * - `round`: Rounded corner
   * - `bevel`: Flat diagonal corner
   */
  linejoin?: StrokeLineJoin | undefined;
  /**
   * Stroke width relative to the viewBox size
   */
  strokeWidth?: number | undefined;
  /**
   * Predefined style to apply to the generated SVG.
   *
   * @remarks
   * - `flat`: Solid fills, no gradients or shadows
   * - `outline`: Stroke-based with minimal or no fills
   * - `duotone`: Two-color design style
   * - `gradient`: Uses gradient fills
   * - `isometric`: 3D isometric projection style
   * - `hand_drawn`: Organic, sketch-like appearance
   */
  stylePreset?: StylePreset | undefined;
};

/** @internal */
export type Design$Outbound = {
  colors?: Colors$Outbound | undefined;
  complexity: number;
  fill_rule: string;
  include_background: boolean;
  linecap: string;
  linejoin: string;
  stroke_width: number;
  style_preset?: string | undefined;
};

/** @internal */
export const Design$outboundSchema: z.ZodType<
  Design$Outbound,
  z.ZodTypeDef,
  Design
> = z.object({
  colors: Colors$outboundSchema.optional(),
  complexity: z.number().int().default(2),
  fillRule: FillRule$outboundSchema.default("nonzero"),
  includeBackground: z.boolean().default(false),
  linecap: StrokeLineCap$outboundSchema.default("round"),
  linejoin: StrokeLineJoin$outboundSchema.default("round"),
  strokeWidth: z.number().default(1.5),
  stylePreset: StylePreset$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    fillRule: "fill_rule",
    includeBackground: "include_background",
    strokeWidth: "stroke_width",
    stylePreset: "style_preset",
  });
});

export function designToJSON(design: Design): string {
  return JSON.stringify(Design$outboundSchema.parse(design));
}
