/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type EditSettings = {
  /**
   * Upper bound for final edit output token count.
   */
  maxOutputTokens?: number | null | undefined;
  /**
   * Optional provider orchestrator token budget.
   */
  orchestratorMaxOutputTokens?: number | null | undefined;
  /**
   * Optional provider shallow edit token budget.
   */
  shallowMaxOutputTokens?: number | null | undefined;
  /**
   * Edit sampling temperature.
   */
  temperature?: number | null | undefined;
};

/** @internal */
export type EditSettings$Outbound = {
  max_output_tokens?: number | null | undefined;
  orchestrator_max_output_tokens?: number | null | undefined;
  shallow_max_output_tokens?: number | null | undefined;
  temperature?: number | null | undefined;
};

/** @internal */
export const EditSettings$outboundSchema: z.ZodType<
  EditSettings$Outbound,
  z.ZodTypeDef,
  EditSettings
> = z.object({
  maxOutputTokens: z.nullable(z.number().int()).optional(),
  orchestratorMaxOutputTokens: z.nullable(z.number().int()).optional(),
  shallowMaxOutputTokens: z.nullable(z.number().int()).optional(),
  temperature: z.nullable(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    maxOutputTokens: "max_output_tokens",
    orchestratorMaxOutputTokens: "orchestrator_max_output_tokens",
    shallowMaxOutputTokens: "shallow_max_output_tokens",
  });
});

export function editSettingsToJSON(editSettings: EditSettings): string {
  return JSON.stringify(EditSettings$outboundSchema.parse(editSettings));
}
