/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  EditSettings,
  EditSettings$Outbound,
  EditSettings$outboundSchema,
} from "./editsettings.js";
import {
  ImageInputReference,
  ImageInputReference$Outbound,
  ImageInputReference$outboundSchema,
} from "./imageinputreference.js";
import {
  SvgInputReference,
  SvgInputReference$Outbound,
  SvgInputReference$outboundSchema,
} from "./svginputreference.js";

/**
 * Reasoning effort applied to this editing. When omitted, Arrow uses its default.
 */
export const EditSVGRequestSchemasReasoningEffort = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Xhigh: "xhigh",
} as const;
/**
 * Reasoning effort applied to this editing. When omitted, Arrow uses its default.
 */
export type EditSVGRequestSchemasReasoningEffort = ClosedEnum<
  typeof EditSVGRequestSchemasReasoningEffort
>;

export type Two = {
  /**
   * Maximum edit review and redo steps after the initial edit.
   */
  maxReviewSteps?: number | undefined;
  /**
   * Model identifier to use for editing.
   */
  model: string;
  /**
   * Instruction describing how to edit the source SVG.
   */
  prompt: string;
  /**
   * Reasoning effort applied to this editing. When omitted, Arrow uses its default.
   */
  reasoningEffort?: EditSVGRequestSchemasReasoningEffort | undefined;
  /**
   * Optional image references for the edit.
   */
  referenceImages?: Array<ImageInputReference> | null | undefined;
  settings?: EditSettings | null | undefined;
  /**
   * When true, emits a Server-Sent Events stream.
   */
  stream?: boolean | undefined;
  svg?: any | null | undefined;
  svgSource: SvgInputReference;
};

/**
 * Reasoning effort applied to this editing. When omitted, Arrow uses its default.
 */
export const EditSVGRequestReasoningEffort = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Xhigh: "xhigh",
} as const;
/**
 * Reasoning effort applied to this editing. When omitted, Arrow uses its default.
 */
export type EditSVGRequestReasoningEffort = ClosedEnum<
  typeof EditSVGRequestReasoningEffort
>;

export type One = {
  /**
   * Maximum edit review and redo steps after the initial edit.
   */
  maxReviewSteps?: number | undefined;
  /**
   * Model identifier to use for editing.
   */
  model: string;
  /**
   * Instruction describing how to edit the source SVG.
   */
  prompt: string;
  /**
   * Reasoning effort applied to this editing. When omitted, Arrow uses its default.
   */
  reasoningEffort?: EditSVGRequestReasoningEffort | undefined;
  /**
   * Optional image references for the edit.
   */
  referenceImages?: Array<ImageInputReference> | null | undefined;
  settings?: EditSettings | null | undefined;
  /**
   * When true, emits a Server-Sent Events stream.
   */
  stream?: boolean | undefined;
  /**
   * Inline SVG markup to edit.
   */
  svg: string;
  svgSource?: any | null | undefined;
};

/**
 * SVG edit request with exactly one non-null source.
 */
export type EditSVGRequest = One | Two;

/** @internal */
export const EditSVGRequestSchemasReasoningEffort$outboundSchema:
  z.ZodNativeEnum<typeof EditSVGRequestSchemasReasoningEffort> = z.nativeEnum(
    EditSVGRequestSchemasReasoningEffort,
  );

/** @internal */
export type Two$Outbound = {
  max_review_steps: number;
  model: string;
  prompt: string;
  reasoning_effort?: string | undefined;
  reference_images?: Array<ImageInputReference$Outbound> | null | undefined;
  settings?: EditSettings$Outbound | null | undefined;
  stream: boolean;
  svg?: any | null | undefined;
  svg_source: SvgInputReference$Outbound;
};

/** @internal */
export const Two$outboundSchema: z.ZodType<Two$Outbound, z.ZodTypeDef, Two> = z
  .object({
    maxReviewSteps: z.number().int().default(0),
    model: z.string(),
    prompt: z.string(),
    reasoningEffort: EditSVGRequestSchemasReasoningEffort$outboundSchema
      .optional(),
    referenceImages: z.nullable(z.array(ImageInputReference$outboundSchema))
      .optional(),
    settings: z.nullable(EditSettings$outboundSchema).optional(),
    stream: z.boolean().default(false),
    svg: z.nullable(z.any()).optional(),
    svgSource: SvgInputReference$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      maxReviewSteps: "max_review_steps",
      reasoningEffort: "reasoning_effort",
      referenceImages: "reference_images",
      svgSource: "svg_source",
    });
  });

export function twoToJSON(two: Two): string {
  return JSON.stringify(Two$outboundSchema.parse(two));
}

/** @internal */
export const EditSVGRequestReasoningEffort$outboundSchema: z.ZodNativeEnum<
  typeof EditSVGRequestReasoningEffort
> = z.nativeEnum(EditSVGRequestReasoningEffort);

/** @internal */
export type One$Outbound = {
  max_review_steps: number;
  model: string;
  prompt: string;
  reasoning_effort?: string | undefined;
  reference_images?: Array<ImageInputReference$Outbound> | null | undefined;
  settings?: EditSettings$Outbound | null | undefined;
  stream: boolean;
  svg: string;
  svg_source?: any | null | undefined;
};

/** @internal */
export const One$outboundSchema: z.ZodType<One$Outbound, z.ZodTypeDef, One> = z
  .object({
    maxReviewSteps: z.number().int().default(0),
    model: z.string(),
    prompt: z.string(),
    reasoningEffort: EditSVGRequestReasoningEffort$outboundSchema.optional(),
    referenceImages: z.nullable(z.array(ImageInputReference$outboundSchema))
      .optional(),
    settings: z.nullable(EditSettings$outboundSchema).optional(),
    stream: z.boolean().default(false),
    svg: z.string(),
    svgSource: z.nullable(z.any()).optional(),
  }).transform((v) => {
    return remap$(v, {
      maxReviewSteps: "max_review_steps",
      reasoningEffort: "reasoning_effort",
      referenceImages: "reference_images",
      svgSource: "svg_source",
    });
  });

export function oneToJSON(one: One): string {
  return JSON.stringify(One$outboundSchema.parse(one));
}

/** @internal */
export type EditSVGRequest$Outbound = One$Outbound | Two$Outbound;

/** @internal */
export const EditSVGRequest$outboundSchema: z.ZodType<
  EditSVGRequest$Outbound,
  z.ZodTypeDef,
  EditSVGRequest
> = z.union([
  z.lazy(() => One$outboundSchema),
  z.lazy(() => Two$outboundSchema),
]);

export function editSVGRequestToJSON(editSVGRequest: EditSVGRequest): string {
  return JSON.stringify(EditSVGRequest$outboundSchema.parse(editSVGRequest));
}
