/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Not Implemented
 */
export type EditSVGRequest = {};

/** @internal */
export type EditSVGRequest$Outbound = {};

/** @internal */
export const EditSVGRequest$outboundSchema: z.ZodType<
  EditSVGRequest$Outbound,
  z.ZodTypeDef,
  EditSVGRequest
> = z.object({});

export function editSVGRequestToJSON(editSVGRequest: EditSVGRequest): string {
  return JSON.stringify(EditSVGRequest$outboundSchema.parse(editSVGRequest));
}
