/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Algorithm for determining inside/outside of complex paths.
 *
 * @remarks
 * - `nonzero`: Standard fill rule
 * - `evenodd`: Alternating fill based on path crossings
 */
export const FillRule = {
  Nonzero: "nonzero",
  Evenodd: "evenodd",
} as const;
/**
 * Algorithm for determining inside/outside of complex paths.
 *
 * @remarks
 * - `nonzero`: Standard fill rule
 * - `evenodd`: Alternating fill based on path crossings
 */
export type FillRule = ClosedEnum<typeof FillRule>;

/** @internal */
export const FillRule$outboundSchema: z.ZodNativeEnum<typeof FillRule> = z
  .nativeEnum(FillRule);
