/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Operation-specific `pricing_credits` are debited once per generated output.
 */
export const Unit = {
  CreditsPerOutput: "credits_per_output",
} as const;
/**
 * Operation-specific `pricing_credits` are debited once per generated output.
 */
export type Unit = ClosedEnum<typeof Unit>;

export type FixedCreditModelBilling = {
  kind: "fixed_credit";
  /**
   * Operation-specific `pricing_credits` are debited once per generated output.
   */
  unit: Unit;
};

/** @internal */
export const Unit$inboundSchema: z.ZodNativeEnum<typeof Unit> = z.nativeEnum(
  Unit,
);

/** @internal */
export const FixedCreditModelBilling$inboundSchema: z.ZodType<
  FixedCreditModelBilling,
  z.ZodTypeDef,
  unknown
> = z.object({
  kind: z.literal("fixed_credit"),
  unit: Unit$inboundSchema,
});

export function fixedCreditModelBillingFromJSON(
  jsonString: string,
): SafeParseResult<FixedCreditModelBilling, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FixedCreditModelBilling$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FixedCreditModelBilling' from JSON`,
  );
}
