/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  ImageInputReferenceInput,
  ImageInputReferenceInput$Outbound,
  ImageInputReferenceInput$outboundSchema,
} from "./imageinputreferenceinput.js";

export type GenerateSVGRequest = {
  /**
   * Additional style or formatting guidance.
   */
  instructions?: string | undefined;
  /**
   * Upper bound for output token count.
   */
  maxOutputTokens?: number | undefined;
  /**
   * Model identifier to use for generation or vectorization.
   */
  model: string;
  /**
   * Number of outputs to generate.
   */
  n?: number | undefined;
  /**
   * Penalty for tokens already present in prior output.
   */
  presencePenalty?: number | null | undefined;
  /**
   * Primary text prompt that describes the desired SVG.
   */
  prompt: string;
  /**
   * Optional reference images to guide style/composition. Accepts `{ url }`, `{ base64 }`, or URL string shorthand.
   */
  references?: Array<ImageInputReferenceInput> | undefined;
  /**
   * When true, emits a Server-Sent Events stream.
   */
  stream?: boolean | undefined;
  /**
   * Sampling temperature.
   */
  temperature?: number | undefined;
  /**
   * Nucleus sampling probability.
   */
  topP?: number | undefined;
};

/** @internal */
export type GenerateSVGRequest$Outbound = {
  instructions?: string | undefined;
  max_output_tokens?: number | undefined;
  model: string;
  n: number;
  presence_penalty: number | null;
  prompt: string;
  references?: Array<ImageInputReferenceInput$Outbound> | undefined;
  stream: boolean;
  temperature: number;
  top_p: number;
};

/** @internal */
export const GenerateSVGRequest$outboundSchema: z.ZodType<
  GenerateSVGRequest$Outbound,
  z.ZodTypeDef,
  GenerateSVGRequest
> = z.object({
  instructions: z.string().optional(),
  maxOutputTokens: z.number().int().optional(),
  model: z.string(),
  n: z.number().int().default(1),
  presencePenalty: z.nullable(z.number().default(0)),
  prompt: z.string(),
  references: z.array(ImageInputReferenceInput$outboundSchema).optional(),
  stream: z.boolean().default(false),
  temperature: z.number().default(1),
  topP: z.number().default(1),
}).transform((v) => {
  return remap$(v, {
    maxOutputTokens: "max_output_tokens",
    presencePenalty: "presence_penalty",
    topP: "top_p",
  });
});

export function generateSVGRequestToJSON(
  generateSVGRequest: GenerateSVGRequest,
): string {
  return JSON.stringify(
    GenerateSVGRequest$outboundSchema.parse(generateSVGRequest),
  );
}
