/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Not Implemented
 */
export type GenerateIconRequest = {};

/** @internal */
export type GenerateIconRequest$Outbound = {};

/** @internal */
export const GenerateIconRequest$outboundSchema: z.ZodType<
  GenerateIconRequest$Outbound,
  z.ZodTypeDef,
  GenerateIconRequest
> = z.object({});

export function generateIconRequestToJSON(
  generateIconRequest: GenerateIconRequest,
): string {
  return JSON.stringify(
    GenerateIconRequest$outboundSchema.parse(generateIconRequest),
  );
}
