/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  ImageInputReference,
  ImageInputReference$Outbound,
  ImageInputReference$outboundSchema,
} from "./imageinputreference.js";

export type GenerateSVGRequest = {
  /**
   * Additional instructions for the model
   */
  instructions?: string | undefined;
  /**
   * Maximum tokens in the output
   */
  maxOutputTokens?: number | undefined;
  /**
   * The model to use for generation/editing
   */
  model: string;
  /**
   * Number of SVGs to generate
   */
  n?: number | undefined;
  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on
   *
   * @remarks
   * whether they appear in the text so far, increasing the model's likelihood
   * to talk about new topics.
   */
  presencePenalty?: number | null | undefined;
  /**
   * The main text prompt describing the desired SVG
   */
  prompt: string;
  /**
   * Optional reference images to guide style/composition.
   *
   * @remarks
   * Maximum of 4 images.
   */
  references?: Array<ImageInputReference> | undefined;
  /**
   * If true, responses are streamed as Server-Sent Events
   */
  stream?: boolean | undefined;
  /**
   * Sampling temperature
   */
  temperature?: number | undefined;
  /**
   * Nucleus sampling parameter
   */
  topP?: number | undefined;
};

/** @internal */
export type GenerateSVGRequest$Outbound = {
  instructions?: string | undefined;
  max_output_tokens?: number | undefined;
  model: string;
  n: number;
  presence_penalty: number | null;
  prompt: string;
  references?: Array<ImageInputReference$Outbound> | undefined;
  stream: boolean;
  temperature: number;
  top_p: number;
};

/** @internal */
export const GenerateSVGRequest$outboundSchema: z.ZodType<
  GenerateSVGRequest$Outbound,
  z.ZodTypeDef,
  GenerateSVGRequest
> = z.object({
  instructions: z.string().optional(),
  maxOutputTokens: z.number().int().optional(),
  model: z.string(),
  n: z.number().int().default(1),
  presencePenalty: z.nullable(z.number().default(0)),
  prompt: z.string(),
  references: z.array(ImageInputReference$outboundSchema).optional(),
  stream: z.boolean().default(false),
  temperature: z.number().default(1),
  topP: z.number().default(1),
}).transform((v) => {
  return remap$(v, {
    maxOutputTokens: "max_output_tokens",
    presencePenalty: "presence_penalty",
    topP: "top_p",
  });
});

export function generateSVGRequestToJSON(
  generateSVGRequest: GenerateSVGRequest,
): string {
  return JSON.stringify(
    GenerateSVGRequest$outboundSchema.parse(generateSVGRequest),
  );
}
