/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  ImageInputReferenceInput,
  ImageInputReferenceInput$Outbound,
  ImageInputReferenceInput$outboundSchema,
} from "./imageinputreferenceinput.js";
import {
  SvgAttributes,
  SvgAttributes$Outbound,
  SvgAttributes$outboundSchema,
} from "./svgattributes.js";

/**
 * Reasoning effort applied to this generation. When omitted, Arrow uses its default.
 */
export const GenerateSVGRequestReasoningEffort = {
  Low: "low",
  Medium: "medium",
  High: "high",
  Xhigh: "xhigh",
} as const;
/**
 * Reasoning effort applied to this generation. When omitted, Arrow uses its default.
 */
export type GenerateSVGRequestReasoningEffort = ClosedEnum<
  typeof GenerateSVGRequestReasoningEffort
>;

export type GenerateSVGRequest = {
  /**
   * Optional SVG root attributes requested by the caller.
   */
  attributes?: SvgAttributes | null | undefined;
  /**
   * Additional style or formatting guidance.
   */
  instructions?: string | undefined;
  /**
   * Upper bound for output token count.
   */
  maxOutputTokens?: number | undefined;
  /**
   * Model identifier to use for generation or vectorization.
   */
  model: string;
  /**
   * Number of outputs to generate.
   */
  n?: number | undefined;
  /**
   * Penalizes tokens already present in output. On native SVG conversion, Arrow 2 defaults to 0 when omitted. Arrow 2 Telos rejects any supplied value, including 0 or null, with HTTP 400; omit this field for Telos.
   */
  presencePenalty?: number | null | undefined;
  /**
   * Primary text prompt that describes the desired SVG.
   */
  prompt: string;
  /**
   * Reasoning effort applied to this generation. When omitted, Arrow uses its default.
   */
  reasoningEffort?: GenerateSVGRequestReasoningEffort | undefined;
  /**
   * Optional reference images to guide style/composition. Accepts `{ url }`, `{ base64 }`, or URL string shorthand. Runtime limits are model-specific, and a request that exceeds the selected model's limit is rejected.
   */
  references?: Array<ImageInputReferenceInput> | undefined;
  /**
   * When true, emits a Server-Sent Events stream.
   */
  stream?: boolean | undefined;
  /**
   * Controls native SVG sampling randomness. Arrow 2 defaults to 1 when omitted. Arrow 2 Telos rejects any supplied value, including 1 or null, with HTTP 400; omit this field for Telos.
   */
  temperature?: number | null | undefined;
  /**
   * Controls native SVG nucleus sampling. Arrow 2 defaults to 1 when omitted. Arrow 2 Telos rejects any supplied value, including 1 or null, with HTTP 400; omit this field for Telos.
   */
  topP?: number | null | undefined;
};

/** @internal */
export const GenerateSVGRequestReasoningEffort$outboundSchema: z.ZodNativeEnum<
  typeof GenerateSVGRequestReasoningEffort
> = z.nativeEnum(GenerateSVGRequestReasoningEffort);

/** @internal */
export type GenerateSVGRequest$Outbound = {
  attributes?: SvgAttributes$Outbound | null | undefined;
  instructions?: string | undefined;
  max_output_tokens?: number | undefined;
  model: string;
  n: number;
  presence_penalty?: number | null | undefined;
  prompt: string;
  reasoning_effort?: string | undefined;
  references?: Array<ImageInputReferenceInput$Outbound> | undefined;
  stream: boolean;
  temperature?: number | null | undefined;
  top_p?: number | null | undefined;
};

/** @internal */
export const GenerateSVGRequest$outboundSchema: z.ZodType<
  GenerateSVGRequest$Outbound,
  z.ZodTypeDef,
  GenerateSVGRequest
> = z.object({
  attributes: z.nullable(SvgAttributes$outboundSchema).optional(),
  instructions: z.string().optional(),
  maxOutputTokens: z.number().int().optional(),
  model: z.string(),
  n: z.number().int().default(1),
  presencePenalty: z.nullable(z.number()).optional(),
  prompt: z.string(),
  reasoningEffort: GenerateSVGRequestReasoningEffort$outboundSchema.optional(),
  references: z.array(ImageInputReferenceInput$outboundSchema).optional(),
  stream: z.boolean().default(false),
  temperature: z.nullable(z.number()).optional(),
  topP: z.nullable(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    maxOutputTokens: "max_output_tokens",
    presencePenalty: "presence_penalty",
    reasoningEffort: "reasoning_effort",
    topP: "top_p",
  });
});

export function generateSVGRequestToJSON(
  generateSVGRequest: GenerateSVGRequest,
): string {
  return JSON.stringify(
    GenerateSVGRequest$outboundSchema.parse(generateSVGRequest),
  );
}
