/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ImageInputReferenceBase64,
  ImageInputReferenceBase64$Outbound,
  ImageInputReferenceBase64$outboundSchema,
} from "./imageinputreferencebase64.js";
import {
  ImageInputReferenceUrl,
  ImageInputReferenceUrl$Outbound,
  ImageInputReferenceUrl$outboundSchema,
} from "./imageinputreferenceurl.js";

/**
 * Reference image input (URL or base64-encoded)
 */
export type ImageInputReference =
  | ImageInputReferenceUrl
  | ImageInputReferenceBase64;

/** @internal */
export type ImageInputReference$Outbound =
  | ImageInputReferenceUrl$Outbound
  | ImageInputReferenceBase64$Outbound;

/** @internal */
export const ImageInputReference$outboundSchema: z.ZodType<
  ImageInputReference$Outbound,
  z.ZodTypeDef,
  ImageInputReference
> = z.union([
  ImageInputReferenceUrl$outboundSchema,
  ImageInputReferenceBase64$outboundSchema,
]);

export function imageInputReferenceToJSON(
  imageInputReference: ImageInputReference,
): string {
  return JSON.stringify(
    ImageInputReference$outboundSchema.parse(imageInputReference),
  );
}
