/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ImageInputReferenceBase64 = {
  /**
   * Base64-encoded image data
   */
  base64: string;
};

/** @internal */
export type ImageInputReferenceBase64$Outbound = {
  base64: string;
};

/** @internal */
export const ImageInputReferenceBase64$outboundSchema: z.ZodType<
  ImageInputReferenceBase64$Outbound,
  z.ZodTypeDef,
  ImageInputReferenceBase64
> = z.object({
  base64: z.string(),
});

export function imageInputReferenceBase64ToJSON(
  imageInputReferenceBase64: ImageInputReferenceBase64,
): string {
  return JSON.stringify(
    ImageInputReferenceBase64$outboundSchema.parse(imageInputReferenceBase64),
  );
}
