/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ImageInputReferenceBase64,
  ImageInputReferenceBase64$Outbound,
  ImageInputReferenceBase64$outboundSchema,
} from "./imageinputreferencebase64.js";
import {
  ImageInputReferenceUrl,
  ImageInputReferenceUrl$Outbound,
  ImageInputReferenceUrl$outboundSchema,
} from "./imageinputreferenceurl.js";

export type ImageInputReferenceInput =
  | ImageInputReferenceUrl
  | ImageInputReferenceBase64
  | string;

/** @internal */
export type ImageInputReferenceInput$Outbound =
  | ImageInputReferenceUrl$Outbound
  | ImageInputReferenceBase64$Outbound
  | string;

/** @internal */
export const ImageInputReferenceInput$outboundSchema: z.ZodType<
  ImageInputReferenceInput$Outbound,
  z.ZodTypeDef,
  ImageInputReferenceInput
> = z.union([
  ImageInputReferenceUrl$outboundSchema,
  ImageInputReferenceBase64$outboundSchema,
  z.string(),
]);

export function imageInputReferenceInputToJSON(
  imageInputReferenceInput: ImageInputReferenceInput,
): string {
  return JSON.stringify(
    ImageInputReferenceInput$outboundSchema.parse(imageInputReferenceInput),
  );
}
