/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ImageInputReferenceBase64 = {
  /**
   * Base64-encoded image payload. Decoded images must be no larger than 12582912 bytes, 4096x4096 pixels, or 16777216 total pixels. Accepted direct media types: image/png, image/jpeg, image/webp, image/gif, image/svg+xml.
   */
  base64: string;
};

/** @internal */
export type ImageInputReferenceBase64$Outbound = {
  base64: string;
};

/** @internal */
export const ImageInputReferenceBase64$outboundSchema: z.ZodType<
  ImageInputReferenceBase64$Outbound,
  z.ZodTypeDef,
  ImageInputReferenceBase64
> = z.object({
  base64: z.string(),
});

export function imageInputReferenceBase64ToJSON(
  imageInputReferenceBase64: ImageInputReferenceBase64,
): string {
  return JSON.stringify(
    ImageInputReferenceBase64$outboundSchema.parse(imageInputReferenceBase64),
  );
}
