/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ImageInputReferenceUrl = {
  /**
   * Network image URL. Only http/https URLs are allowed.
   */
  url: string;
};

/** @internal */
export type ImageInputReferenceUrl$Outbound = {
  url: string;
};

/** @internal */
export const ImageInputReferenceUrl$outboundSchema: z.ZodType<
  ImageInputReferenceUrl$Outbound,
  z.ZodTypeDef,
  ImageInputReferenceUrl
> = z.object({
  url: z.string(),
});

export function imageInputReferenceUrlToJSON(
  imageInputReferenceUrl: ImageInputReferenceUrl,
): string {
  return JSON.stringify(
    ImageInputReferenceUrl$outboundSchema.parse(imageInputReferenceUrl),
  );
}
