/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ImageInputReferenceBase64,
  ImageInputReferenceBase64$Outbound,
  ImageInputReferenceBase64$outboundSchema,
} from "./imageinputreferencebase64.js";
import {
  ImageInputReferenceUrl,
  ImageInputReferenceUrl$Outbound,
  ImageInputReferenceUrl$outboundSchema,
} from "./imageinputreferenceurl.js";

/**
 * Image input reference. Accepts a network image URL or a base64-encoded image payload. Decoded images must be no larger than 12582912 bytes, 4096x4096 pixels, or 16777216 total pixels. Accepted direct media types: image/png, image/jpeg, image/webp, image/gif, image/svg+xml.
 */
export type ImageInputReference =
  | ImageInputReferenceUrl
  | ImageInputReferenceBase64;

/** @internal */
export type ImageInputReference$Outbound =
  | ImageInputReferenceUrl$Outbound
  | ImageInputReferenceBase64$Outbound;

/** @internal */
export const ImageInputReference$outboundSchema: z.ZodType<
  ImageInputReference$Outbound,
  z.ZodTypeDef,
  ImageInputReference
> = z.union([
  ImageInputReferenceUrl$outboundSchema,
  ImageInputReferenceBase64$outboundSchema,
]);

export function imageInputReferenceToJSON(
  imageInputReference: ImageInputReference,
): string {
  return JSON.stringify(
    ImageInputReference$outboundSchema.parse(imageInputReference),
  );
}
