/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type InputReference = {
  /**
   * Image URL or base64 data URI
   */
  url: string;
};

/** @internal */
export type InputReference$Outbound = {
  url: string;
};

/** @internal */
export const InputReference$outboundSchema: z.ZodType<
  InputReference$Outbound,
  z.ZodTypeDef,
  InputReference
> = z.object({
  url: z.string(),
});

export function inputReferenceToJSON(inputReference: InputReference): string {
  return JSON.stringify(InputReference$outboundSchema.parse(inputReference));
}
