/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Model, Model$inboundSchema } from "./model.js";

export const ObjectT = {
  List: "list",
} as const;
export type ObjectT = ClosedEnum<typeof ObjectT>;

export type ListModelsResponse = {
  data: Array<Model>;
  object: ObjectT;
};

/** @internal */
export const ObjectT$inboundSchema: z.ZodNativeEnum<typeof ObjectT> = z
  .nativeEnum(ObjectT);

/** @internal */
export const ListModelsResponse$inboundSchema: z.ZodType<
  ListModelsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Model$inboundSchema),
  object: ObjectT$inboundSchema,
});

export function listModelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListModelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListModelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListModelsResponse' from JSON`,
  );
}
