/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Input/output modality type.
 */
export const Modality = {
  Text: "text",
  Image: "image",
  Svg: "svg",
} as const;
/**
 * Input/output modality type.
 */
export type Modality = ClosedEnum<typeof Modality>;

/** @internal */
export const Modality$inboundSchema: z.ZodNativeEnum<typeof Modality> = z
  .nativeEnum(Modality);
