/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FixedCreditModelBilling,
  FixedCreditModelBilling$inboundSchema,
} from "./fixedcreditmodelbilling.js";
import {
  TokenUsageModelBilling,
  TokenUsageModelBilling$inboundSchema,
} from "./tokenusagemodelbilling.js";

export type ModelBilling = FixedCreditModelBilling | TokenUsageModelBilling;

/** @internal */
export const ModelBilling$inboundSchema: z.ZodType<
  ModelBilling,
  z.ZodTypeDef,
  unknown
> = z.union([
  FixedCreditModelBilling$inboundSchema,
  TokenUsageModelBilling$inboundSchema,
]);

export function modelBillingFromJSON(
  jsonString: string,
): SafeParseResult<ModelBilling, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelBilling$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelBilling' from JSON`,
  );
}
