/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const ModelIdsShared = {
  Arrow05: "arrow-0.5",
  Arrow05Preview: "arrow-0.5-preview",
} as const;
export type ModelIdsShared = ClosedEnum<typeof ModelIdsShared>;

/** @internal */
export const ModelIdsShared$outboundSchema: z.ZodNativeEnum<
  typeof ModelIdsShared
> = z.nativeEnum(ModelIdsShared);
