/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ModelBilling, ModelBilling$inboundSchema } from "./modelbilling.js";

export const InputModalities = {
  Text: "text",
  Image: "image",
  Svg: "svg",
} as const;
export type InputModalities = ClosedEnum<typeof InputModalities>;

export const ModelObject = {
  Model: "model",
} as const;
export type ModelObject = ClosedEnum<typeof ModelObject>;

export const OutputModalities = {
  Text: "text",
  Image: "image",
  Svg: "svg",
} as const;
export type OutputModalities = ClosedEnum<typeof OutputModalities>;

/**
 * Deprecated. Prefer `pricing_credits` for operation-specific debits per generated output. USD strings are legacy placeholders.
 *
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type Pricing = {
  /**
   * Deprecated — use `pricing_credits`. Legacy USD price string per generated animated SVG for an SVG animation operation.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  svgAnimate?: string | undefined;
  /**
   * Deprecated — use `pricing_credits`. Legacy USD price string per generated SVG for an SVG edit operation.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  svgEdit?: string | undefined;
  /**
   * Deprecated — use `pricing_credits`. Legacy USD price string per generated SVG for an SVG generation operation.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  svgGenerate: string;
  /**
   * Deprecated — use `pricing_credits`. Legacy USD price string per generated SVG for an SVG vectorization operation.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  svgVectorize: string;
};

export type PricingCredits = {
  /**
   * Credits debited from the organization balance per generated animated SVG for this model's SVG animation operation.
   */
  svgAnimate?: number | undefined;
  /**
   * Credits debited from the organization balance per generated SVG for this model's SVG edit operation.
   */
  svgEdit?: number | undefined;
  /**
   * Credits debited from the organization balance per generated SVG for this model's SVG generation operation.
   */
  svgGenerate: number;
  /**
   * Credits debited from the organization balance per generated SVG for this model's SVG vectorization operation.
   */
  svgVectorize: number;
};

export const SupportedOperations = {
  OpenResponses: "open_responses",
  SvgGenerate: "svg_generate",
  SvgEdit: "svg_edit",
  SvgAnimate: "svg_animate",
  SvgVectorize: "svg_vectorize",
} as const;
export type SupportedOperations = ClosedEnum<typeof SupportedOperations>;

export const SupportedSamplingParameters = {
  Temperature: "temperature",
  TopP: "top_p",
  TopK: "top_k",
  RepetitionPenalty: "repetition_penalty",
  PresencePenalty: "presence_penalty",
  Stop: "stop",
} as const;
export type SupportedSamplingParameters = ClosedEnum<
  typeof SupportedSamplingParameters
>;

export type Model = {
  billing: ModelBilling;
  contextLength?: number | undefined;
  created: number;
  description?: string | undefined;
  id: string;
  inputModalities?: Array<InputModalities> | undefined;
  maxOutputLength?: number | undefined;
  name?: string | undefined;
  object: ModelObject;
  outputModalities?: Array<OutputModalities> | undefined;
  ownedBy: string;
  /**
   * Deprecated. Prefer `pricing_credits` for operation-specific debits per generated output. USD strings are legacy placeholders.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  pricing?: Pricing | undefined;
  pricingCredits?: PricingCredits | undefined;
  supportedOperations?: Array<SupportedOperations> | undefined;
  supportedSamplingParameters?: Array<SupportedSamplingParameters> | undefined;
};

/** @internal */
export const InputModalities$inboundSchema: z.ZodNativeEnum<
  typeof InputModalities
> = z.nativeEnum(InputModalities);

/** @internal */
export const ModelObject$inboundSchema: z.ZodNativeEnum<typeof ModelObject> = z
  .nativeEnum(ModelObject);

/** @internal */
export const OutputModalities$inboundSchema: z.ZodNativeEnum<
  typeof OutputModalities
> = z.nativeEnum(OutputModalities);

/** @internal */
export const Pricing$inboundSchema: z.ZodType<Pricing, z.ZodTypeDef, unknown> =
  z.object({
    svg_animate: z.string().optional(),
    svg_edit: z.string().optional(),
    svg_generate: z.string(),
    svg_vectorize: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "svg_animate": "svgAnimate",
      "svg_edit": "svgEdit",
      "svg_generate": "svgGenerate",
      "svg_vectorize": "svgVectorize",
    });
  });

export function pricingFromJSON(
  jsonString: string,
): SafeParseResult<Pricing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pricing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pricing' from JSON`,
  );
}

/** @internal */
export const PricingCredits$inboundSchema: z.ZodType<
  PricingCredits,
  z.ZodTypeDef,
  unknown
> = z.object({
  svg_animate: z.number().int().optional(),
  svg_edit: z.number().int().optional(),
  svg_generate: z.number().int(),
  svg_vectorize: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "svg_animate": "svgAnimate",
    "svg_edit": "svgEdit",
    "svg_generate": "svgGenerate",
    "svg_vectorize": "svgVectorize",
  });
});

export function pricingCreditsFromJSON(
  jsonString: string,
): SafeParseResult<PricingCredits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PricingCredits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PricingCredits' from JSON`,
  );
}

/** @internal */
export const SupportedOperations$inboundSchema: z.ZodNativeEnum<
  typeof SupportedOperations
> = z.nativeEnum(SupportedOperations);

/** @internal */
export const SupportedSamplingParameters$inboundSchema: z.ZodNativeEnum<
  typeof SupportedSamplingParameters
> = z.nativeEnum(SupportedSamplingParameters);

/** @internal */
export const Model$inboundSchema: z.ZodType<Model, z.ZodTypeDef, unknown> = z
  .object({
    billing: ModelBilling$inboundSchema,
    context_length: z.number().int().optional(),
    created: z.number().int(),
    description: z.string().optional(),
    id: z.string(),
    input_modalities: z.array(InputModalities$inboundSchema).optional(),
    max_output_length: z.number().int().optional(),
    name: z.string().optional(),
    object: ModelObject$inboundSchema,
    output_modalities: z.array(OutputModalities$inboundSchema).optional(),
    owned_by: z.string(),
    pricing: z.lazy(() => Pricing$inboundSchema).optional(),
    pricing_credits: z.lazy(() => PricingCredits$inboundSchema).optional(),
    supported_operations: z.array(SupportedOperations$inboundSchema).optional(),
    supported_sampling_parameters: z.array(
      SupportedSamplingParameters$inboundSchema,
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "context_length": "contextLength",
      "input_modalities": "inputModalities",
      "max_output_length": "maxOutputLength",
      "output_modalities": "outputModalities",
      "owned_by": "ownedBy",
      "pricing_credits": "pricingCredits",
      "supported_operations": "supportedOperations",
      "supported_sampling_parameters": "supportedSamplingParameters",
    });
  });

export function modelFromJSON(
  jsonString: string,
): SafeParseResult<Model, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Model$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Model' from JSON`,
  );
}
