/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Pricing information for the model (per token, in USD as strings to avoid floating point issues).
 */
export type ModelPricing = {
  /**
   * Price per output token in USD.
   */
  completion: string;
  /**
   * Price per image in USD.
   */
  image?: string | undefined;
  /**
   * Price per cached input token read in USD.
   */
  inputCacheReads?: string | undefined;
  /**
   * Price per cached input token write in USD.
   */
  inputCacheWrites?: string | undefined;
  /**
   * Price per input token in USD.
   */
  prompt: string;
  /**
   * Price per request in USD.
   */
  request?: string | undefined;
};

/** @internal */
export const ModelPricing$inboundSchema: z.ZodType<
  ModelPricing,
  z.ZodTypeDef,
  unknown
> = z.object({
  completion: z.string(),
  image: z.string().optional(),
  input_cache_reads: z.string().optional(),
  input_cache_writes: z.string().optional(),
  prompt: z.string(),
  request: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "input_cache_reads": "inputCacheReads",
    "input_cache_writes": "inputCacheWrites",
  });
});

export function modelPricingFromJSON(
  jsonString: string,
): SafeParseResult<ModelPricing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelPricing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelPricing' from JSON`,
  );
}
