/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PublicErrorSseEventDataCode = {
  InvalidRequest: "invalid_request",
  InvalidApiKey: "invalid_api_key",
  Unauthorized: "unauthorized",
  FundingPaymentFailed: "funding_payment_failed",
  FundingPaymentMethodRequired: "funding_payment_method_required",
  FundingPaymentActionRequired: "funding_payment_action_required",
  FundingPending: "funding_pending",
  InsufficientCredits: "insufficient_credits",
  AccountFrozen: "account_frozen",
  ContentPolicyViolation: "content_policy_violation",
  ModelNotFound: "model_not_found",
  PayloadTooLarge: "payload_too_large",
  RequestTimeout: "request_timeout",
  RateLimitExceeded: "rate_limit_exceeded",
  OperationRateLimitExceeded: "operation_rate_limit_exceeded",
  WeeklyLimitExceeded: "weekly_limit_exceeded",
  ServerError: "server_error",
  ModelError: "model_error",
  ModelUnavailable: "model_unavailable",
} as const;
export type PublicErrorSseEventDataCode = ClosedEnum<
  typeof PublicErrorSseEventDataCode
>;

export const Type = {
  Error: "error",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type PublicErrorSseEventData = {
  code: PublicErrorSseEventDataCode;
  message: string;
  requestId: string;
  status: number;
  type: Type;
};

/** @internal */
export const PublicErrorSseEventDataCode$inboundSchema: z.ZodNativeEnum<
  typeof PublicErrorSseEventDataCode
> = z.nativeEnum(PublicErrorSseEventDataCode);

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const PublicErrorSseEventData$inboundSchema: z.ZodType<
  PublicErrorSseEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: PublicErrorSseEventDataCode$inboundSchema,
  message: z.string(),
  request_id: z.string(),
  status: z.number().int(),
  type: Type$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});

export function publicErrorSseEventDataFromJSON(
  jsonString: string,
): SafeParseResult<PublicErrorSseEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicErrorSseEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicErrorSseEventData' from JSON`,
  );
}
