/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Code = {
  InvalidRequest: "invalid_request",
  InvalidApiKey: "invalid_api_key",
  Unauthorized: "unauthorized",
  FundingPaymentFailed: "funding_payment_failed",
  FundingPaymentMethodRequired: "funding_payment_method_required",
  FundingPaymentActionRequired: "funding_payment_action_required",
  FundingPending: "funding_pending",
  InsufficientCredits: "insufficient_credits",
  AccountFrozen: "account_frozen",
  ContentPolicyViolation: "content_policy_violation",
  ModelNotFound: "model_not_found",
  PayloadTooLarge: "payload_too_large",
  RequestTimeout: "request_timeout",
  RateLimitExceeded: "rate_limit_exceeded",
  OperationRateLimitExceeded: "operation_rate_limit_exceeded",
  WeeklyLimitExceeded: "weekly_limit_exceeded",
  ServerError: "server_error",
  ModelError: "model_error",
  ModelUnavailable: "model_unavailable",
} as const;
export type Code = ClosedEnum<typeof Code>;

export type PublicErrorEnvelope = {
  code: Code;
  message: string;
  /**
   * The request parameter the failure is about, as a path from the request body root: `size.width`, `input[0].content`. A parameter name, never a submitted value. The same field, with the same meaning, as `param` on the Open Responses error payload, so one name reads across a failure raised before streaming and one raised during it. Absent, rather than null, when the failure is not about one particular parameter.
   */
  param?: string | undefined;
  requestId: string;
  retryAfter?: number | undefined;
  status: number;
};

/** @internal */
export const Code$inboundSchema: z.ZodNativeEnum<typeof Code> = z.nativeEnum(
  Code,
);

/** @internal */
export const PublicErrorEnvelope$inboundSchema: z.ZodType<
  PublicErrorEnvelope,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: Code$inboundSchema,
  message: z.string(),
  param: z.string().optional(),
  request_id: z.string(),
  retry_after: z.number().int().optional(),
  status: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "retry_after": "retryAfter",
  });
});

export function publicErrorEnvelopeFromJSON(
  jsonString: string,
): SafeParseResult<PublicErrorEnvelope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicErrorEnvelope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicErrorEnvelope' from JSON`,
  );
}
