/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CreateSVGRequest,
  CreateSVGRequest$Outbound,
  CreateSVGRequest$outboundSchema,
} from "./createsvgrequest.js";
import {
  EditSVGRequest,
  EditSVGRequest$Outbound,
  EditSVGRequest$outboundSchema,
} from "./editsvgrequest.js";

export type QuiverMessage = CreateSVGRequest | EditSVGRequest;

/** @internal */
export type QuiverMessage$Outbound =
  | CreateSVGRequest$Outbound
  | EditSVGRequest$Outbound;

/** @internal */
export const QuiverMessage$outboundSchema: z.ZodType<
  QuiverMessage$Outbound,
  z.ZodTypeDef,
  QuiverMessage
> = z.union([CreateSVGRequest$outboundSchema, EditSVGRequest$outboundSchema]);

export function quiverMessageToJSON(quiverMessage: QuiverMessage): string {
  return JSON.stringify(QuiverMessage$outboundSchema.parse(quiverMessage));
}
