/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * How safe zone values are interpreted.
 *
 * @remarks
 * - `relative`: Values are 0-1 representing percentage of viewport
 * - `absolute`: Values are in SVG coordinate units
 */
export const SafeZoneMode = {
  Relative: "relative",
  Absolute: "absolute",
} as const;
/**
 * How safe zone values are interpreted.
 *
 * @remarks
 * - `relative`: Values are 0-1 representing percentage of viewport
 * - `absolute`: Values are in SVG coordinate units
 */
export type SafeZoneMode = ClosedEnum<typeof SafeZoneMode>;

/** @internal */
export const SafeZoneMode$outboundSchema: z.ZodNativeEnum<typeof SafeZoneMode> =
  z.nativeEnum(SafeZoneMode);
