/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { SafeZoneMode, SafeZoneMode$outboundSchema } from "./safezonemode.js";
import {
  SafeZoneOverrides,
  SafeZoneOverrides$Outbound,
  SafeZoneOverrides$outboundSchema,
} from "./safezoneoverrides.js";

/**
 * The "Safe Zone" is the guaranteed empty margin between content and edge.
 *
 * @remarks
 * Prevents clipping and bad cropping.
 */
export type SafeZone = {
  /**
   * How safe zone values are interpreted.
   *
   * @remarks
   * - `relative`: Values are 0-1 representing percentage of viewport
   * - `absolute`: Values are in SVG coordinate units
   */
  mode?: SafeZoneMode | undefined;
  /**
   * Optional overrides for specific sides of the safe zone
   */
  overrides?: SafeZoneOverrides | undefined;
  /**
   * Padding value (interpretation depends on mode)
   */
  value?: number | undefined;
};

/** @internal */
export type SafeZone$Outbound = {
  mode: string;
  overrides?: SafeZoneOverrides$Outbound | undefined;
  value: number;
};

/** @internal */
export const SafeZone$outboundSchema: z.ZodType<
  SafeZone$Outbound,
  z.ZodTypeDef,
  SafeZone
> = z.object({
  mode: SafeZoneMode$outboundSchema.default("relative"),
  overrides: SafeZoneOverrides$outboundSchema.optional(),
  value: z.number().default(0.1),
});

export function safeZoneToJSON(safeZone: SafeZone): string {
  return JSON.stringify(SafeZone$outboundSchema.parse(safeZone));
}
