/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Optional overrides for specific sides of the safe zone
 */
export type SafeZoneOverrides = {
  /**
   * Override value for bottom margin
   */
  bottom?: number | undefined;
  /**
   * Override value for left margin
   */
  left?: number | undefined;
  /**
   * Override value for right margin
   */
  right?: number | undefined;
  /**
   * Override value for top margin
   */
  top?: number | undefined;
};

/** @internal */
export type SafeZoneOverrides$Outbound = {
  bottom?: number | undefined;
  left?: number | undefined;
  right?: number | undefined;
  top?: number | undefined;
};

/** @internal */
export const SafeZoneOverrides$outboundSchema: z.ZodType<
  SafeZoneOverrides$Outbound,
  z.ZodTypeDef,
  SafeZoneOverrides
> = z.object({
  bottom: z.number().optional(),
  left: z.number().optional(),
  right: z.number().optional(),
  top: z.number().optional(),
});

export function safeZoneOverridesToJSON(
  safeZoneOverrides: SafeZoneOverrides,
): string {
  return JSON.stringify(
    SafeZoneOverrides$outboundSchema.parse(safeZoneOverrides),
  );
}
