/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Supported sampling parameter.
 */
export const SamplingParameter = {
  Temperature: "temperature",
  TopP: "top_p",
  TopK: "top_k",
  RepetitionPenalty: "repetition_penalty",
  PresencePenalty: "presence_penalty",
  Stop: "stop",
} as const;
/**
 * Supported sampling parameter.
 */
export type SamplingParameter = ClosedEnum<typeof SamplingParameter>;

/** @internal */
export const SamplingParameter$inboundSchema: z.ZodNativeEnum<
  typeof SamplingParameter
> = z.nativeEnum(SamplingParameter);
