/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The shape at the corners where paths meet.
 *
 * @remarks
 * - `miter`: Sharp pointed corner
 * - `round`: Rounded corner
 * - `bevel`: Flat diagonal corner
 */
export const StrokeLineJoin = {
  Miter: "miter",
  Round: "round",
  Bevel: "bevel",
} as const;
/**
 * The shape at the corners where paths meet.
 *
 * @remarks
 * - `miter`: Sharp pointed corner
 * - `round`: Rounded corner
 * - `bevel`: Flat diagonal corner
 */
export type StrokeLineJoin = ClosedEnum<typeof StrokeLineJoin>;

/** @internal */
export const StrokeLineJoin$outboundSchema: z.ZodNativeEnum<
  typeof StrokeLineJoin
> = z.nativeEnum(StrokeLineJoin);
