/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The shape at the end of open paths.
 *
 * @remarks
 * - `butt`: Flat edge at the exact endpoint
 * - `round`: Rounded edge extending past endpoint
 * - `square`: Square edge extending past endpoint
 */
export const StrokeLineCap = {
  Butt: "butt",
  Round: "round",
  Square: "square",
} as const;
/**
 * The shape at the end of open paths.
 *
 * @remarks
 * - `butt`: Flat edge at the exact endpoint
 * - `round`: Rounded edge extending past endpoint
 * - `square`: Square edge extending past endpoint
 */
export type StrokeLineCap = ClosedEnum<typeof StrokeLineCap>;

/** @internal */
export const StrokeLineCap$outboundSchema: z.ZodNativeEnum<
  typeof StrokeLineCap
> = z.nativeEnum(StrokeLineCap);
