/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Predefined style to apply to the generated SVG.
 *
 * @remarks
 * - `flat`: Solid fills, no gradients or shadows
 * - `outline`: Stroke-based with minimal or no fills
 * - `duotone`: Two-color design style
 * - `gradient`: Uses gradient fills
 * - `isometric`: 3D isometric projection style
 * - `hand_drawn`: Organic, sketch-like appearance
 */
export const StylePreset = {
  Flat: "flat",
  Outline: "outline",
  Duotone: "duotone",
  Gradient: "gradient",
  Isometric: "isometric",
  HandDrawn: "hand_drawn",
} as const;
/**
 * Predefined style to apply to the generated SVG.
 *
 * @remarks
 * - `flat`: Solid fills, no gradients or shadows
 * - `outline`: Stroke-based with minimal or no fills
 * - `duotone`: Two-color design style
 * - `gradient`: Uses gradient fills
 * - `isometric`: 3D isometric projection style
 * - `hand_drawn`: Organic, sketch-like appearance
 */
export type StylePreset = ClosedEnum<typeof StylePreset>;

/** @internal */
export const StylePreset$outboundSchema: z.ZodNativeEnum<typeof StylePreset> = z
  .nativeEnum(StylePreset);
