/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * API operation that the model supports.
 */
export const SupportedOperation = {
  SvgGenerate: "svg_generate",
  SvgEdit: "svg_edit",
  SvgAnimate: "svg_animate",
  SvgVectorize: "svg_vectorize",
  SvgCollections: "svg_collections",
  ChatCompletions: "chat_completions",
} as const;
/**
 * API operation that the model supports.
 */
export type SupportedOperation = ClosedEnum<typeof SupportedOperation>;

/** @internal */
export const SupportedOperation$inboundSchema: z.ZodNativeEnum<
  typeof SupportedOperation
> = z.nativeEnum(SupportedOperation);
