/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SVGAnimateReasoningEventData = {
  /**
   * A unique identifier for the SVG animation.
   */
  id: string;
  /**
   * Reasoning text about animation decisions.
   */
  text: string;
};

/**
 * Model reasoning about SVG animation approach.
 */
export type SVGAnimateReasoningEvent = {
  data: SVGAnimateReasoningEventData;
  event: "svg_animate.reasoning";
};

/** @internal */
export const SVGAnimateReasoningEventData$inboundSchema: z.ZodType<
  SVGAnimateReasoningEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  text: z.string(),
});

export function svgAnimateReasoningEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGAnimateReasoningEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGAnimateReasoningEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGAnimateReasoningEventData' from JSON`,
  );
}

/** @internal */
export const SVGAnimateReasoningEvent$inboundSchema: z.ZodType<
  SVGAnimateReasoningEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGAnimateReasoningEventData$inboundSchema)),
  event: z.literal("svg_animate.reasoning"),
});

export function svgAnimateReasoningEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGAnimateReasoningEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGAnimateReasoningEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGAnimateReasoningEvent' from JSON`,
  );
}
