/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type SVGAnimateInput = {
  /**
   * Additional instructions for the model
   */
  instructions?: string | undefined;
  /**
   * Description of the desired animation
   */
  motionPrompt: string;
  /**
   * Source SVG for editing operations (inline SVG markup or URL)
   */
  source: string;
};

/** @internal */
export type SVGAnimateInput$Outbound = {
  instructions?: string | undefined;
  motion_prompt: string;
  source: string;
};

/** @internal */
export const SVGAnimateInput$outboundSchema: z.ZodType<
  SVGAnimateInput$Outbound,
  z.ZodTypeDef,
  SVGAnimateInput
> = z.object({
  instructions: z.string().optional(),
  motionPrompt: z.string(),
  source: z.string(),
}).transform((v) => {
  return remap$(v, {
    motionPrompt: "motion_prompt",
  });
});

export function svgAnimateInputToJSON(
  svgAnimateInput: SVGAnimateInput,
): string {
  return JSON.stringify(SVGAnimateInput$outboundSchema.parse(svgAnimateInput));
}
