/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SVGAnimateDraftEventData = {
  /**
   * A unique identifier for the SVG animation.
   */
  id: string;
  /**
   * Partial animated SVG markup.
   */
  svg: string;
};

/**
 * Streaming partial SVG chunks during animation generation.
 */
export type SVGAnimateDraftEvent = {
  data: SVGAnimateDraftEventData;
  event: "svg_animate.draft";
};

/** @internal */
export const SVGAnimateDraftEventData$inboundSchema: z.ZodType<
  SVGAnimateDraftEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  svg: z.string(),
});

export function svgAnimateDraftEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGAnimateDraftEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGAnimateDraftEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGAnimateDraftEventData' from JSON`,
  );
}

/** @internal */
export const SVGAnimateDraftEvent$inboundSchema: z.ZodType<
  SVGAnimateDraftEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGAnimateDraftEventData$inboundSchema)),
  event: z.literal("svg_animate.draft"),
});

export function svgAnimateDraftEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGAnimateDraftEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGAnimateDraftEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGAnimateDraftEvent' from JSON`,
  );
}
