/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type Data = {
  /**
   * A unique identifier for the SVG animation.
   */
  id: string;
  /**
   * Complete animated SVG markup.
   */
  svg: string;
  usage?: Usage | undefined;
};

/**
 * Final postprocessed, optimized animated SVG.
 */
export type SVGAnimateContentEvent = {
  data: Data;
  event: "svg_animate.content";
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string(),
    svg: z.string(),
    usage: Usage$inboundSchema.optional(),
  });

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const SVGAnimateContentEvent$inboundSchema: z.ZodType<
  SVGAnimateContentEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => Data$inboundSchema)),
  event: z.literal("svg_animate.content"),
});

export function svgAnimateContentEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGAnimateContentEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGAnimateContentEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGAnimateContentEvent' from JSON`,
  );
}
