/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * SVG root viewBox attribute controls.
 */
export type ViewBox = {
  /**
   * Height of the SVG viewBox. Must be greater than zero.
   */
  height: number;
  /**
   * Minimum x coordinate of the SVG viewBox.
   */
  minX: number;
  /**
   * Minimum y coordinate of the SVG viewBox.
   */
  minY: number;
  /**
   * Width of the SVG viewBox. Must be greater than zero.
   */
  width: number;
};

/**
 * Optional SVG root attributes requested by the caller.
 */
export type SvgAttributes = {
  /**
   * SVG root viewBox attribute controls.
   */
  viewBox?: ViewBox | null | undefined;
};

/** @internal */
export type ViewBox$Outbound = {
  height: number;
  minX: number;
  minY: number;
  width: number;
};

/** @internal */
export const ViewBox$outboundSchema: z.ZodType<
  ViewBox$Outbound,
  z.ZodTypeDef,
  ViewBox
> = z.object({
  height: z.number(),
  minX: z.number(),
  minY: z.number(),
  width: z.number(),
});

export function viewBoxToJSON(viewBox: ViewBox): string {
  return JSON.stringify(ViewBox$outboundSchema.parse(viewBox));
}

/** @internal */
export type SvgAttributes$Outbound = {
  viewBox?: ViewBox$Outbound | null | undefined;
};

/** @internal */
export const SvgAttributes$outboundSchema: z.ZodType<
  SvgAttributes$Outbound,
  z.ZodTypeDef,
  SvgAttributes
> = z.object({
  viewBox: z.nullable(z.lazy(() => ViewBox$outboundSchema)).optional(),
});

export function svgAttributesToJSON(svgAttributes: SvgAttributes): string {
  return JSON.stringify(SvgAttributes$outboundSchema.parse(svgAttributes));
}
