/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SvgUsage, SvgUsage$inboundSchema } from "./svgusage.js";

export type SvgContentEventData = {
  /**
   * Credit cost for this completed SVG output. Emitted on `content` events.
   */
  credits?: number | undefined;
  /**
   * A unique identifier for the SVG output. For streaming multi-output requests (`n > 1`), each output has a distinct `id` and all events for that output reuse that same `id`.
   */
  id: string;
  /**
   * Zero-based output index for this event. Present for multi-output streams (`n > 1`).
   */
  index?: number | undefined;
  /**
   * Loop period for the generated animation in milliseconds.
   */
  loopPeriodMs?: number | null | undefined;
  /**
   * Opening animation duration in milliseconds.
   */
  openingAnimationMs?: number | null | undefined;
  /**
   * The SVG markup (partial during draft, complete during content).
   */
  svg: string;
  /**
   * Optional reasoning text (present on reasoning events for some operations).
   */
  text?: string | undefined;
  type: "content";
  /**
   * Deprecated. Use `credits` for billing values.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  usage?: SvgUsage | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const SvgContentEventData$inboundSchema: z.ZodType<
  SvgContentEventData,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    credits: z.number().int().optional(),
    id: z.string(),
    index: z.number().int().optional(),
    loop_period_ms: z.nullable(z.number().int()).optional(),
    opening_animation_ms: z.nullable(z.number().int()).optional(),
    svg: z.string(),
    text: z.string().optional(),
    type: z.literal("content"),
    usage: SvgUsage$inboundSchema.optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "loop_period_ms": "loopPeriodMs",
    "opening_animation_ms": "openingAnimationMs",
  });
});

export function svgContentEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SvgContentEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SvgContentEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SvgContentEventData' from JSON`,
  );
}
