/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const SupportedModes = {
  Icon: "icon",
  Illustration: "illustration",
  Logo: "logo",
} as const;
export type SupportedModes = ClosedEnum<typeof SupportedModes>;

export const SupportedStyles = {
  Flat: "flat",
  Outline: "outline",
  Duotone: "duotone",
  Gradient: "gradient",
} as const;
export type SupportedStyles = ClosedEnum<typeof SupportedStyles>;

/**
 * SVG-specific capabilities and recommendations for the model.
 */
export type SVGCapabilities = {
  /**
   * Maximum complexity level (1-4) the model can handle well.
   */
  maxComplexity?: number | undefined;
  /**
   * Recommended viewBox sizes for optimal output quality.
   */
  recommendedViewboxSizes?: Array<number> | undefined;
  /**
   * SVG generation modes the model excels at.
   */
  supportedModes?: Array<SupportedModes> | undefined;
  /**
   * Style presets the model supports.
   */
  supportedStyles?: Array<SupportedStyles> | undefined;
};

/** @internal */
export const SupportedModes$inboundSchema: z.ZodNativeEnum<
  typeof SupportedModes
> = z.nativeEnum(SupportedModes);

/** @internal */
export const SupportedStyles$inboundSchema: z.ZodNativeEnum<
  typeof SupportedStyles
> = z.nativeEnum(SupportedStyles);

/** @internal */
export const SVGCapabilities$inboundSchema: z.ZodType<
  SVGCapabilities,
  z.ZodTypeDef,
  unknown
> = z.object({
  max_complexity: z.number().int().optional(),
  recommended_viewbox_sizes: z.array(z.number().int()).optional(),
  supported_modes: z.array(SupportedModes$inboundSchema).optional(),
  supported_styles: z.array(SupportedStyles$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "max_complexity": "maxComplexity",
    "recommended_viewbox_sizes": "recommendedViewboxSizes",
    "supported_modes": "supportedModes",
    "supported_styles": "supportedStyles",
  });
});

export function svgCapabilitiesFromJSON(
  jsonString: string,
): SafeParseResult<SVGCapabilities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGCapabilities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGCapabilities' from JSON`,
  );
}
