/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const MimeType = {
  ImageSvgPlusXml: "image/svg+xml",
} as const;
export type MimeType = ClosedEnum<typeof MimeType>;

export type SvgDocument = {
  mimeType: MimeType;
  /**
   * Raw SVG markup.
   */
  svg: string;
};

/** @internal */
export const MimeType$inboundSchema: z.ZodNativeEnum<typeof MimeType> = z
  .nativeEnum(MimeType);

/** @internal */
export const SvgDocument$inboundSchema: z.ZodType<
  SvgDocument,
  z.ZodTypeDef,
  unknown
> = z.object({
  mime_type: MimeType$inboundSchema,
  svg: z.string(),
}).transform((v) => {
  return remap$(v, {
    "mime_type": "mimeType",
  });
});

export function svgDocumentFromJSON(
  jsonString: string,
): SafeParseResult<SvgDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SvgDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SvgDocument' from JSON`,
  );
}
