/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SvgUsage, SvgUsage$inboundSchema } from "./svgusage.js";

export type SvgDraftEventData = {
  /**
   * A unique identifier for the SVG output. For streaming multi-output requests (`n > 1`), each output has a distinct `id` and all events for that output reuse that same `id`.
   */
  id: string;
  /**
   * Zero-based output index for this event. Present for multi-output streams (`n > 1`).
   */
  index?: number | undefined;
  /**
   * The SVG markup (partial during draft, complete during content).
   */
  svg: string;
  /**
   * Optional reasoning text (present on reasoning events for some operations).
   */
  text?: string | undefined;
  type: "draft";
  /**
   * Deprecated. Use `credits` for billing values.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  usage?: SvgUsage | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const SvgDraftEventData$inboundSchema: z.ZodType<
  SvgDraftEventData,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.string(),
    index: z.number().int().optional(),
    svg: z.string(),
    text: z.string().optional(),
    type: z.literal("draft"),
    usage: SvgUsage$inboundSchema.optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);

export function svgDraftEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SvgDraftEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SvgDraftEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SvgDraftEventData' from JSON`,
  );
}
