/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * MIME type of the SVG
 */
export const MimeType = {
  ImageSvgPlusXml: "image/svg+xml",
} as const;
/**
 * MIME type of the SVG
 */
export type MimeType = ClosedEnum<typeof MimeType>;

export type SVGDocument = {
  /**
   * MIME type of the SVG
   */
  mimeType: MimeType;
  /**
   * The generated SVG markup
   */
  svg: string;
};

/** @internal */
export const MimeType$inboundSchema: z.ZodNativeEnum<typeof MimeType> = z
  .nativeEnum(MimeType);

/** @internal */
export const SVGDocument$inboundSchema: z.ZodType<
  SVGDocument,
  z.ZodTypeDef,
  unknown
> = z.object({
  mime_type: MimeType$inboundSchema,
  svg: z.string(),
}).transform((v) => {
  return remap$(v, {
    "mime_type": "mimeType",
  });
});

export function svgDocumentFromJSON(
  jsonString: string,
): SafeParseResult<SVGDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGDocument' from JSON`,
  );
}
