/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SvgUsage, SvgUsage$inboundSchema } from "./svgusage.js";

/**
 * Whether this draft SVG appends to the prior draft or replaces it with a full snapshot.
 */
export const UpdateType = {
  Delta: "delta",
  Snapshot: "snapshot",
} as const;
/**
 * Whether this draft SVG appends to the prior draft or replaces it with a full snapshot.
 */
export type UpdateType = ClosedEnum<typeof UpdateType>;

export type SvgDraftEventData = {
  /**
   * A unique identifier for the SVG output. For streaming multi-output requests (`n > 1`), each output has a distinct `id` and all events for that output reuse that same `id`.
   */
  id: string;
  /**
   * Zero-based output index for this event. Present for multi-output streams (`n > 1`).
   */
  index?: number | undefined;
  /**
   * The SVG markup (partial during draft, complete during content).
   */
  svg: string;
  /**
   * Optional reasoning text (present on reasoning events for some operations).
   */
  text?: string | undefined;
  type: "draft";
  /**
   * Whether this draft SVG appends to the prior draft or replaces it with a full snapshot.
   */
  updateType?: UpdateType | undefined;
  /**
   * Token totals for token-priced models. Fixed-credit models use `credits` for billing and may report compatibility zeros here.
   */
  usage?: SvgUsage | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const UpdateType$inboundSchema: z.ZodNativeEnum<typeof UpdateType> = z
  .nativeEnum(UpdateType);

/** @internal */
export const SvgDraftEventData$inboundSchema: z.ZodType<
  SvgDraftEventData,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.string(),
    index: z.number().int().optional(),
    svg: z.string(),
    text: z.string().optional(),
    type: z.literal("draft"),
    update_type: UpdateType$inboundSchema.optional(),
    usage: SvgUsage$inboundSchema.optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "update_type": "updateType",
  });
});

export function svgDraftEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SvgDraftEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SvgDraftEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SvgDraftEventData' from JSON`,
  );
}
