/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type SVGEditContentEventData = {
  /**
   * A unique identifier for the SVG edit.
   */
  id: string;
  /**
   * Complete edited SVG markup.
   */
  svg: string;
  usage?: Usage | undefined;
};

/**
 * Final postprocessed, optimized edited SVG.
 */
export type SVGEditContentEvent = {
  data: SVGEditContentEventData;
  event: "svg_edit.content";
};

/** @internal */
export const SVGEditContentEventData$inboundSchema: z.ZodType<
  SVGEditContentEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  svg: z.string(),
  usage: Usage$inboundSchema.optional(),
});

export function svgEditContentEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGEditContentEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGEditContentEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGEditContentEventData' from JSON`,
  );
}

/** @internal */
export const SVGEditContentEvent$inboundSchema: z.ZodType<
  SVGEditContentEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGEditContentEventData$inboundSchema)),
  event: z.literal("svg_edit.content"),
});

export function svgEditContentEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGEditContentEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGEditContentEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGEditContentEvent' from JSON`,
  );
}
