/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  InputReference,
  InputReference$Outbound,
  InputReference$outboundSchema,
} from "./inputreference.js";

/**
 * Input configuration for text-to-SVG generation
 */
export type SVGEditInput = {
  /**
   * Additional instructions for the model
   */
  instructions?: string | undefined;
  /**
   * The main text prompt describing the desired SVG
   */
  prompt: string;
  /**
   * Optional reference images to guide style/composition
   */
  references?: Array<InputReference> | undefined;
  /**
   * Source SVG for editing operations (inline SVG markup or URL)
   */
  source: string;
};

/** @internal */
export type SVGEditInput$Outbound = {
  instructions?: string | undefined;
  prompt: string;
  references?: Array<InputReference$Outbound> | undefined;
  source: string;
};

/** @internal */
export const SVGEditInput$outboundSchema: z.ZodType<
  SVGEditInput$Outbound,
  z.ZodTypeDef,
  SVGEditInput
> = z.object({
  instructions: z.string().optional(),
  prompt: z.string(),
  references: z.array(InputReference$outboundSchema).optional(),
  source: z.string(),
});

export function svgEditInputToJSON(svgEditInput: SVGEditInput): string {
  return JSON.stringify(SVGEditInput$outboundSchema.parse(svgEditInput));
}
