/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SVGEditReasoningEventData = {
  /**
   * A unique identifier for the SVG edit.
   */
  id: string;
  /**
   * Reasoning text about edit decisions.
   */
  text: string;
};

/**
 * Model reasoning about SVG edit approach.
 */
export type SVGEditReasoningEvent = {
  data: SVGEditReasoningEventData;
  event: "svg_edit.reasoning";
};

/** @internal */
export const SVGEditReasoningEventData$inboundSchema: z.ZodType<
  SVGEditReasoningEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  text: z.string(),
});

export function svgEditReasoningEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGEditReasoningEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGEditReasoningEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGEditReasoningEventData' from JSON`,
  );
}

/** @internal */
export const SVGEditReasoningEvent$inboundSchema: z.ZodType<
  SVGEditReasoningEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGEditReasoningEventData$inboundSchema)),
  event: z.literal("svg_edit.reasoning"),
});

export function svgEditReasoningEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGEditReasoningEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGEditReasoningEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGEditReasoningEvent' from JSON`,
  );
}
