/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SVGEditDraftEventData = {
  /**
   * A unique identifier for the SVG edit.
   */
  id: string;
  /**
   * Partial SVG markup during editing.
   */
  svg: string;
};

/**
 * Streaming partial SVG chunks during editing.
 */
export type SVGEditDraftEvent = {
  data: SVGEditDraftEventData;
  event: "svg_edit.draft";
};

/** @internal */
export const SVGEditDraftEventData$inboundSchema: z.ZodType<
  SVGEditDraftEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  svg: z.string(),
});

export function svgEditDraftEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGEditDraftEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGEditDraftEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGEditDraftEventData' from JSON`,
  );
}

/** @internal */
export const SVGEditDraftEvent$inboundSchema: z.ZodType<
  SVGEditDraftEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGEditDraftEventData$inboundSchema)),
  event: z.literal("svg_edit.draft"),
});

export function svgEditDraftEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGEditDraftEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGEditDraftEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGEditDraftEvent' from JSON`,
  );
}
