/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SVGGenerateDraftEventData = {
  /**
   * A unique identifier for the SVG generation.
   */
  id: string;
  /**
   * Partial SVG markup during streaming.
   */
  svg: string;
};

/**
 * Streaming partial SVG chunks as generated by the model.
 */
export type SVGGenerateDraftEvent = {
  data: SVGGenerateDraftEventData;
  event: "svg_generate.draft";
};

/** @internal */
export const SVGGenerateDraftEventData$inboundSchema: z.ZodType<
  SVGGenerateDraftEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  svg: z.string(),
});

export function svgGenerateDraftEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGGenerateDraftEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGGenerateDraftEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGGenerateDraftEventData' from JSON`,
  );
}

/** @internal */
export const SVGGenerateDraftEvent$inboundSchema: z.ZodType<
  SVGGenerateDraftEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGGenerateDraftEventData$inboundSchema)),
  event: z.literal("svg_generate.draft"),
});

export function svgGenerateDraftEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGGenerateDraftEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGGenerateDraftEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGGenerateDraftEvent' from JSON`,
  );
}
