/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SVGGenerateReasoningEventData = {
  /**
   * A unique identifier for the SVG generation.
   */
  id: string;
  /**
   * Reasoning text about design decisions.
   */
  text: string;
};

/**
 * Model reasoning about SVG design approach.
 */
export type SVGGenerateReasoningEvent = {
  data: SVGGenerateReasoningEventData;
  event: "svg_generate.reasoning";
};

/** @internal */
export const SVGGenerateReasoningEventData$inboundSchema: z.ZodType<
  SVGGenerateReasoningEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  text: z.string(),
});

export function svgGenerateReasoningEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGGenerateReasoningEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGGenerateReasoningEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGGenerateReasoningEventData' from JSON`,
  );
}

/** @internal */
export const SVGGenerateReasoningEvent$inboundSchema: z.ZodType<
  SVGGenerateReasoningEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGGenerateReasoningEventData$inboundSchema)),
  event: z.literal("svg_generate.reasoning"),
});

export function svgGenerateReasoningEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGGenerateReasoningEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGGenerateReasoningEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGGenerateReasoningEvent' from JSON`,
  );
}
