/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type SVGGenerateContentEventData = {
  /**
   * A unique identifier for the SVG generation.
   */
  id: string;
  /**
   * Complete, optimized SVG markup.
   */
  svg: string;
  usage?: Usage | undefined;
};

/**
 * Final postprocessed, optimized SVG.
 */
export type SVGGenerateContentEvent = {
  data: SVGGenerateContentEventData;
  event: "svg_generate.content";
};

/** @internal */
export const SVGGenerateContentEventData$inboundSchema: z.ZodType<
  SVGGenerateContentEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  svg: z.string(),
  usage: Usage$inboundSchema.optional(),
});

export function svgGenerateContentEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGGenerateContentEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGGenerateContentEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGGenerateContentEventData' from JSON`,
  );
}

/** @internal */
export const SVGGenerateContentEvent$inboundSchema: z.ZodType<
  SVGGenerateContentEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGGenerateContentEventData$inboundSchema)),
  event: z.literal("svg_generate.content"),
});

export function svgGenerateContentEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGGenerateContentEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGGenerateContentEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGGenerateContentEvent' from JSON`,
  );
}
