/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  InputReference,
  InputReference$Outbound,
  InputReference$outboundSchema,
} from "./inputreference.js";

/**
 * Input configuration for text-to-SVG generation
 */
export type SVGInput = {
  /**
   * Additional instructions for the model
   */
  instructions?: string | undefined;
  /**
   * The main text prompt describing the desired SVG
   */
  prompt: string;
  /**
   * Optional reference images to guide style/composition
   */
  references?: Array<InputReference> | undefined;
};

/** @internal */
export type SVGInput$Outbound = {
  instructions?: string | undefined;
  prompt: string;
  references?: Array<InputReference$Outbound> | undefined;
};

/** @internal */
export const SVGInput$outboundSchema: z.ZodType<
  SVGInput$Outbound,
  z.ZodTypeDef,
  SVGInput
> = z.object({
  instructions: z.string().optional(),
  prompt: z.string(),
  references: z.array(InputReference$outboundSchema).optional(),
});

export function svgInputToJSON(svgInput: SVGInput): string {
  return JSON.stringify(SVGInput$outboundSchema.parse(svgInput));
}
