/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  SvgInputReferenceBase64,
  SvgInputReferenceBase64$Outbound,
  SvgInputReferenceBase64$outboundSchema,
} from "./svginputreferencebase64.js";
import {
  SvgInputReferenceUrl,
  SvgInputReferenceUrl$Outbound,
  SvgInputReferenceUrl$outboundSchema,
} from "./svginputreferenceurl.js";

/**
 * Remote or base64-encoded SVG source to animate.
 */
export type SvgInputReference = SvgInputReferenceUrl | SvgInputReferenceBase64;

/** @internal */
export type SvgInputReference$Outbound =
  | SvgInputReferenceUrl$Outbound
  | SvgInputReferenceBase64$Outbound;

/** @internal */
export const SvgInputReference$outboundSchema: z.ZodType<
  SvgInputReference$Outbound,
  z.ZodTypeDef,
  SvgInputReference
> = z.union([
  SvgInputReferenceUrl$outboundSchema,
  SvgInputReferenceBase64$outboundSchema,
]);

export function svgInputReferenceToJSON(
  svgInputReference: SvgInputReference,
): string {
  return JSON.stringify(
    SvgInputReference$outboundSchema.parse(svgInputReference),
  );
}
