/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SvgInputReferenceUrl = {
  /**
   * Network SVG URL. Only http/https URLs are allowed.
   */
  url: string;
};

/** @internal */
export type SvgInputReferenceUrl$Outbound = {
  url: string;
};

/** @internal */
export const SvgInputReferenceUrl$outboundSchema: z.ZodType<
  SvgInputReferenceUrl$Outbound,
  z.ZodTypeDef,
  SvgInputReferenceUrl
> = z.object({
  url: z.string(),
});

export function svgInputReferenceUrlToJSON(
  svgInputReferenceUrl: SvgInputReferenceUrl,
): string {
  return JSON.stringify(
    SvgInputReferenceUrl$outboundSchema.parse(svgInputReferenceUrl),
  );
}
