/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SvgInputReferenceBase64 = {
  /**
   * Base64-encoded SVG payload.
   */
  base64: string;
};

/** @internal */
export type SvgInputReferenceBase64$Outbound = {
  base64: string;
};

/** @internal */
export const SvgInputReferenceBase64$outboundSchema: z.ZodType<
  SvgInputReferenceBase64$Outbound,
  z.ZodTypeDef,
  SvgInputReferenceBase64
> = z.object({
  base64: z.string(),
});

export function svgInputReferenceBase64ToJSON(
  svgInputReferenceBase64: SvgInputReferenceBase64,
): string {
  return JSON.stringify(
    SvgInputReferenceBase64$outboundSchema.parse(svgInputReferenceBase64),
  );
}
