/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The generation mode optimized for different use cases.
 *
 * @remarks
 * - `icon`: Optimized for small sizes, usually square, distinct shapes
 * - `illustration`: Optimized for scenes, larger viewports, complex details
 * - `logo`: Optimized for uniqueness, strong silhouettes, text-compatible
 */
export const SVGMode = {
  Icon: "icon",
  Illustration: "illustration",
  Logo: "logo",
} as const;
/**
 * The generation mode optimized for different use cases.
 *
 * @remarks
 * - `icon`: Optimized for small sizes, usually square, distinct shapes
 * - `illustration`: Optimized for scenes, larger viewports, complex details
 * - `logo`: Optimized for uniqueness, strong silhouettes, text-compatible
 */
export type SVGMode = ClosedEnum<typeof SVGMode>;

/** @internal */
export const SVGMode$outboundSchema: z.ZodNativeEnum<typeof SVGMode> = z
  .nativeEnum(SVGMode);
