/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { Canvas, Canvas$Outbound, Canvas$outboundSchema } from "./canvas.js";
import {
  Constraints,
  Constraints$Outbound,
  Constraints$outboundSchema,
} from "./constraints.js";
import { Design, Design$Outbound, Design$outboundSchema } from "./design.js";
import { SVGMode, SVGMode$outboundSchema } from "./svgmode.js";

/**
 * SVG-specific generation parameters for controlling canvas, design, and styling.
 *
 * @remarks
 * These parameters give fine-grained control over the generated SVG output.
 */
export type SVGParams = {
  /**
   * Controls the coordinate system and "Safe Zones" to prevent clipping/bad cropping.
   *
   * @remarks
   * NOTE: "mode" determines the default canvas if this is omitted.
   */
  canvas?: Canvas | undefined;
  /**
   * Limits and constraints for the generated SVG output
   */
  constraints?: Constraints | undefined;
  /**
   * Controls how the model applies aesthetics to the generated SVG
   */
  design?: Design | undefined;
  /**
   * The generation mode optimized for different use cases.
   *
   * @remarks
   * - `icon`: Optimized for small sizes, usually square, distinct shapes
   * - `illustration`: Optimized for scenes, larger viewports, complex details
   * - `logo`: Optimized for uniqueness, strong silhouettes, text-compatible
   */
  mode?: SVGMode | undefined;
};

/** @internal */
export type SVGParams$Outbound = {
  canvas?: Canvas$Outbound | undefined;
  constraints?: Constraints$Outbound | undefined;
  design?: Design$Outbound | undefined;
  mode: string;
};

/** @internal */
export const SVGParams$outboundSchema: z.ZodType<
  SVGParams$Outbound,
  z.ZodTypeDef,
  SVGParams
> = z.object({
  canvas: Canvas$outboundSchema.optional(),
  constraints: Constraints$outboundSchema.optional(),
  design: Design$outboundSchema.optional(),
  mode: SVGMode$outboundSchema.default("icon"),
});

export function svgParamsToJSON(svgParams: SVGParams): string {
  return JSON.stringify(SVGParams$outboundSchema.parse(svgParams));
}
