/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SvgUsage, SvgUsage$inboundSchema } from "./svgusage.js";

export type SvgReasoningEventData = {
  /**
   * A unique identifier for the SVG output when available. Stable per output across streamed events.
   */
  id?: string | undefined;
  /**
   * Zero-based output index for this event. Present for multi-output streams (`n > 1`).
   */
  index?: number | undefined;
  /**
   * Optional SVG payload for forward compatibility.
   */
  svg?: string | undefined;
  /**
   * Optional reasoning text (present on reasoning events for some operations).
   */
  text?: string | undefined;
  type: "reasoning";
  usage?: SvgUsage | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const SvgReasoningEventData$inboundSchema: z.ZodType<
  SvgReasoningEventData,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.string().optional(),
    index: z.number().int().optional(),
    svg: z.string().optional(),
    text: z.string().optional(),
    type: z.literal("reasoning"),
    usage: SvgUsage$inboundSchema.optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);

export function svgReasoningEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SvgReasoningEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SvgReasoningEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SvgReasoningEventData' from JSON`,
  );
}
