/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SVGDocument, SVGDocument$inboundSchema } from "./svgdocument.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type SVGResponse = {
  /**
   * Unix timestamp of when the response was created
   */
  created: number;
  /**
   * Array of generated SVG documents
   */
  data: Array<SVGDocument>;
  /**
   * A unique identifier for the SVG generation.
   */
  id: string;
  usage?: Usage | undefined;
};

/** @internal */
export const SVGResponse$inboundSchema: z.ZodType<
  SVGResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.number().int(),
  data: z.array(SVGDocument$inboundSchema),
  id: z.string(),
  usage: Usage$inboundSchema.optional(),
});

export function svgResponseFromJSON(
  jsonString: string,
): SafeParseResult<SVGResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGResponse' from JSON`,
  );
}
