/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SvgDocument, SvgDocument$inboundSchema } from "./svgdocument.js";
import { SvgUsage, SvgUsage$inboundSchema } from "./svgusage.js";

export type SvgResponse = {
  created: number;
  /**
   * Credit cost for fixed-credit models. Omitted for token-priced models, whose measured totals are returned in `usage`.
   */
  credits?: number | undefined;
  data: Array<SvgDocument>;
  id: string;
  /**
   * Token totals for token-priced models. Fixed-credit models use `credits` for billing and may report compatibility zeros here.
   */
  usage?: SvgUsage | undefined;
};

/** @internal */
export const SvgResponse$inboundSchema: z.ZodType<
  SvgResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.number().int(),
  credits: z.number().int().optional(),
  data: z.array(SvgDocument$inboundSchema),
  id: z.string(),
  usage: SvgUsage$inboundSchema.optional(),
});

export function svgResponseFromJSON(
  jsonString: string,
): SafeParseResult<SvgResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SvgResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SvgResponse' from JSON`,
  );
}
