/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

/**
 * The event type indicating the phase.
 */
export const Type = {
  Reasoning: "reasoning",
  Draft: "draft",
  Content: "content",
} as const;
/**
 * The event type indicating the phase.
 */
export type Type = ClosedEnum<typeof Type>;

/**
 * JSON payload for SVG streaming SSE events (sent in the `data:` line).
 */
export type SVGStreamEventData = {
  /**
   * A unique identifier for the SVG operation.
   */
  id: string;
  /**
   * The SVG markup (partial during draft, complete during content).
   */
  svg: string;
  /**
   * Optional reasoning text (present on reasoning events for some operations).
   */
  text?: string | undefined;
  /**
   * The event type indicating the phase.
   */
  type: Type;
  usage?: Usage | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const SVGStreamEventData$inboundSchema: z.ZodType<
  SVGStreamEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  svg: z.string(),
  text: z.string().optional(),
  type: Type$inboundSchema,
  usage: Usage$inboundSchema.optional(),
});

export function svgStreamEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGStreamEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGStreamEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGStreamEventData' from JSON`,
  );
}
