/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SvgContentEventData,
  SvgContentEventData$inboundSchema,
} from "./svgcontenteventdata.js";
import {
  SvgDraftEventData,
  SvgDraftEventData$inboundSchema,
} from "./svgdrafteventdata.js";
import {
  SvgGeneratingEventData,
  SvgGeneratingEventData$inboundSchema,
} from "./svggeneratingeventdata.js";
import {
  SvgReasoningEventData,
  SvgReasoningEventData$inboundSchema,
} from "./svgreasoningeventdata.js";

/**
 * The event payload. Shape depends on the `type` phase discriminator.
 */
export type SvgStreamEventData =
  | SvgContentEventData
  | SvgDraftEventData
  | SvgGeneratingEventData
  | SvgReasoningEventData;

/** @internal */
export const SvgStreamEventData$inboundSchema: z.ZodType<
  SvgStreamEventData,
  z.ZodTypeDef,
  unknown
> = z.union([
  SvgContentEventData$inboundSchema,
  SvgDraftEventData$inboundSchema,
  SvgGeneratingEventData$inboundSchema,
  SvgReasoningEventData$inboundSchema,
]);

export function svgStreamEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SvgStreamEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SvgStreamEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SvgStreamEventData' from JSON`,
  );
}
