/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SVGStreamEventData,
  SVGStreamEventData$inboundSchema,
} from "./svgstreameventdata.js";

/**
 * The SSE event name (sent via the `event:` line).
 */
export const Event = {
  Reasoning: "reasoning",
  Draft: "draft",
  Content: "content",
} as const;
/**
 * The SSE event name (sent via the `event:` line).
 */
export type Event = ClosedEnum<typeof Event>;

/**
 * Server-sent event (SSE) envelope for SVG streaming operations.
 *
 * @remarks
 *
 * Speakeasy expects SSE event schemas to only declare the canonical SSE fields
 * (`id`, `event`, `data`, `retry`) at the top level. The server uses the SSE `event:`
 * line for the phase discriminator and the `data:` line for a JSON payload.
 */
export type SVGStreamEvent = {
  /**
   * JSON payload for SVG streaming SSE events (sent in the `data:` line).
   */
  data: SVGStreamEventData;
  /**
   * The SSE event name (sent via the `event:` line).
   */
  event: Event;
  /**
   * Optional SSE event id (sent via the `id:` line).
   */
  id?: string | undefined;
  /**
   * Optional SSE retry value in milliseconds (sent via the `retry:` line).
   */
  retry?: number | undefined;
};

/** @internal */
export const Event$inboundSchema: z.ZodNativeEnum<typeof Event> = z.nativeEnum(
  Event,
);

/** @internal */
export const SVGStreamEvent$inboundSchema: z.ZodType<
  SVGStreamEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(SVGStreamEventData$inboundSchema),
  event: Event$inboundSchema,
  id: z.string().optional(),
  retry: z.number().int().optional(),
});

export function svgStreamEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGStreamEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGStreamEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGStreamEvent' from JSON`,
  );
}
