/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SVGAnimateContentEvent,
  SVGAnimateContentEvent$inboundSchema,
} from "./svganimatecontentevent.js";
import {
  SVGAnimateDraftEvent,
  SVGAnimateDraftEvent$inboundSchema,
} from "./svganimatedraftevent.js";
import {
  SVGAnimateReasoningEvent,
  SVGAnimateReasoningEvent$inboundSchema,
} from "./svganimatereasoningevent.js";
import {
  SVGEditContentEvent,
  SVGEditContentEvent$inboundSchema,
} from "./svgeditcontentevent.js";
import {
  SVGEditDraftEvent,
  SVGEditDraftEvent$inboundSchema,
} from "./svgeditdraftevent.js";
import {
  SVGEditReasoningEvent,
  SVGEditReasoningEvent$inboundSchema,
} from "./svgeditreasoningevent.js";
import {
  SVGVectorizeContentEvent,
  SVGVectorizeContentEvent$inboundSchema,
} from "./svgvectorizecontentevent.js";
import {
  SVGVectorizeDraftEvent,
  SVGVectorizeDraftEvent$inboundSchema,
} from "./svgvectorizedraftevent.js";
import {
  SVGVectorizeReasoningEvent,
  SVGVectorizeReasoningEvent$inboundSchema,
} from "./svgvectorizereasoningevent.js";

/**
 * Streaming event for SVG generation (SSE format).
 *
 * @remarks
 * Events flow in three phases:
 * 1. `*.reasoning` - Model thinking about design approach (optional)
 * 2. `*.draft` - Streaming partial SVG chunks as generated
 * 3. `*.content` - Final postprocessed, optimized SVG
 */
export type SVGStreamEvent =
  | SVGAnimateContentEvent
  | SVGAnimateDraftEvent
  | SVGAnimateReasoningEvent
  | SVGEditContentEvent
  | SVGEditDraftEvent
  | SVGEditReasoningEvent
  | SVGVectorizeContentEvent
  | SVGVectorizeDraftEvent
  | SVGVectorizeReasoningEvent;

/** @internal */
export const SVGStreamEvent$inboundSchema: z.ZodType<
  SVGStreamEvent,
  z.ZodTypeDef,
  unknown
> = z.union([
  SVGAnimateContentEvent$inboundSchema,
  SVGAnimateDraftEvent$inboundSchema,
  SVGAnimateReasoningEvent$inboundSchema,
  SVGEditContentEvent$inboundSchema,
  SVGEditDraftEvent$inboundSchema,
  SVGEditReasoningEvent$inboundSchema,
  SVGVectorizeContentEvent$inboundSchema,
  SVGVectorizeDraftEvent$inboundSchema,
  SVGVectorizeReasoningEvent$inboundSchema,
]);

export function svgStreamEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGStreamEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGStreamEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGStreamEvent' from JSON`,
  );
}
