/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Deprecated. Use `credits` for billing values.
 *
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type SvgUsage = {
  /**
   * Deprecated. Token counts are retained for compatibility and may be zeroed.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  inputTokens: number;
  /**
   * Deprecated. Token counts are retained for compatibility and may be zeroed.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  outputTokens: number;
  /**
   * Deprecated. Token counts are retained for compatibility and may be zeroed.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  totalTokens: number;
};

/** @internal */
export const SvgUsage$inboundSchema: z.ZodType<
  SvgUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  input_tokens: z.number().int(),
  output_tokens: z.number().int(),
  total_tokens: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "input_tokens": "inputTokens",
    "output_tokens": "outputTokens",
    "total_tokens": "totalTokens",
  });
});

export function svgUsageFromJSON(
  jsonString: string,
): SafeParseResult<SvgUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SvgUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SvgUsage' from JSON`,
  );
}
