/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  InputReference,
  InputReference$Outbound,
  InputReference$outboundSchema,
} from "./inputreference.js";

/**
 * Input configuration for image-to-SVG vectorization
 */
export type SVGVectorizeInput = {
  image: InputReference;
  /**
   * Optional instructions for vectorization style
   */
  instructions?: string | undefined;
};

/** @internal */
export type SVGVectorizeInput$Outbound = {
  image: InputReference$Outbound;
  instructions?: string | undefined;
};

/** @internal */
export const SVGVectorizeInput$outboundSchema: z.ZodType<
  SVGVectorizeInput$Outbound,
  z.ZodTypeDef,
  SVGVectorizeInput
> = z.object({
  image: InputReference$outboundSchema,
  instructions: z.string().optional(),
});

export function svgVectorizeInputToJSON(
  svgVectorizeInput: SVGVectorizeInput,
): string {
  return JSON.stringify(
    SVGVectorizeInput$outboundSchema.parse(svgVectorizeInput),
  );
}
