/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SVGVectorizeReasoningEventData = {
  /**
   * A unique identifier for the SVG creation.
   */
  id: string;
  /**
   * Reasoning text about design decisions.
   */
  text: string;
};

/**
 * Model reasoning about SVG design approach.
 */
export type SVGVectorizeReasoningEvent = {
  data: SVGVectorizeReasoningEventData;
  event: "svg_vectorize.reasoning";
};

/** @internal */
export const SVGVectorizeReasoningEventData$inboundSchema: z.ZodType<
  SVGVectorizeReasoningEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  text: z.string(),
});

export function svgVectorizeReasoningEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGVectorizeReasoningEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGVectorizeReasoningEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGVectorizeReasoningEventData' from JSON`,
  );
}

/** @internal */
export const SVGVectorizeReasoningEvent$inboundSchema: z.ZodType<
  SVGVectorizeReasoningEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGVectorizeReasoningEventData$inboundSchema)),
  event: z.literal("svg_vectorize.reasoning"),
});

export function svgVectorizeReasoningEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGVectorizeReasoningEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGVectorizeReasoningEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGVectorizeReasoningEvent' from JSON`,
  );
}
