/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Usage, Usage$inboundSchema } from "./usage.js";

export type SVGVectorizeContentEventData = {
  /**
   * A unique identifier for the vectorization.
   */
  id: string;
  /**
   * Complete, optimized vectorized SVG markup.
   */
  svg: string;
  usage?: Usage | undefined;
};

/**
 * Final postprocessed, optimized vectorized SVG.
 */
export type SVGVectorizeContentEvent = {
  data: SVGVectorizeContentEventData;
  event: "svg_vectorize.content";
};

/** @internal */
export const SVGVectorizeContentEventData$inboundSchema: z.ZodType<
  SVGVectorizeContentEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  svg: z.string(),
  usage: Usage$inboundSchema.optional(),
});

export function svgVectorizeContentEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGVectorizeContentEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGVectorizeContentEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGVectorizeContentEventData' from JSON`,
  );
}

/** @internal */
export const SVGVectorizeContentEvent$inboundSchema: z.ZodType<
  SVGVectorizeContentEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGVectorizeContentEventData$inboundSchema)),
  event: z.literal("svg_vectorize.content"),
});

export function svgVectorizeContentEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGVectorizeContentEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGVectorizeContentEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGVectorizeContentEvent' from JSON`,
  );
}
