/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SVGVectorizeDraftEventData = {
  /**
   * A unique identifier for the SVG creation.
   */
  id: string;
  /**
   * Partial SVG markup during streaming.
   */
  svg: string;
};

/**
 * Streaming partial SVG chunks as generated by the model.
 */
export type SVGVectorizeDraftEvent = {
  data: SVGVectorizeDraftEventData;
  event: "svg_vectorize.draft";
};

/** @internal */
export const SVGVectorizeDraftEventData$inboundSchema: z.ZodType<
  SVGVectorizeDraftEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  svg: z.string(),
});

export function svgVectorizeDraftEventDataFromJSON(
  jsonString: string,
): SafeParseResult<SVGVectorizeDraftEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGVectorizeDraftEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGVectorizeDraftEventData' from JSON`,
  );
}

/** @internal */
export const SVGVectorizeDraftEvent$inboundSchema: z.ZodType<
  SVGVectorizeDraftEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(z.lazy(() => SVGVectorizeDraftEventData$inboundSchema)),
  event: z.literal("svg_vectorize.draft"),
});

export function svgVectorizeDraftEventFromJSON(
  jsonString: string,
): SafeParseResult<SVGVectorizeDraftEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SVGVectorizeDraftEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SVGVectorizeDraftEvent' from JSON`,
  );
}
