/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Currency = {
  Usd: "USD",
} as const;
export type Currency = ClosedEnum<typeof Currency>;

export const PricingModel = {
  TokenUsageV1: "token_usage_v1",
} as const;
export type PricingModel = ClosedEnum<typeof PricingModel>;

export type Rates = {
  cacheWrite: number;
  cachedInput: number;
  input: number;
  output: number;
};

export const TokenUsageModelBillingUnit = {
  MillicentsPerMillionTokens: "millicents_per_million_tokens",
} as const;
export type TokenUsageModelBillingUnit = ClosedEnum<
  typeof TokenUsageModelBillingUnit
>;

export type TokenUsageModelBilling = {
  currency: Currency;
  kind: "token_usage";
  pricingModel: PricingModel;
  rates: Rates;
  unit: TokenUsageModelBillingUnit;
};

/** @internal */
export const Currency$inboundSchema: z.ZodNativeEnum<typeof Currency> = z
  .nativeEnum(Currency);

/** @internal */
export const PricingModel$inboundSchema: z.ZodNativeEnum<typeof PricingModel> =
  z.nativeEnum(PricingModel);

/** @internal */
export const Rates$inboundSchema: z.ZodType<Rates, z.ZodTypeDef, unknown> = z
  .object({
    cache_write: z.number().int(),
    cached_input: z.number().int(),
    input: z.number().int(),
    output: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "cache_write": "cacheWrite",
      "cached_input": "cachedInput",
    });
  });

export function ratesFromJSON(
  jsonString: string,
): SafeParseResult<Rates, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Rates$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Rates' from JSON`,
  );
}

/** @internal */
export const TokenUsageModelBillingUnit$inboundSchema: z.ZodNativeEnum<
  typeof TokenUsageModelBillingUnit
> = z.nativeEnum(TokenUsageModelBillingUnit);

/** @internal */
export const TokenUsageModelBilling$inboundSchema: z.ZodType<
  TokenUsageModelBilling,
  z.ZodTypeDef,
  unknown
> = z.object({
  currency: Currency$inboundSchema,
  kind: z.literal("token_usage"),
  pricing_model: PricingModel$inboundSchema,
  rates: z.lazy(() => Rates$inboundSchema),
  unit: TokenUsageModelBillingUnit$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "pricing_model": "pricingModel",
  });
});

export function tokenUsageModelBillingFromJSON(
  jsonString: string,
): SafeParseResult<TokenUsageModelBilling, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TokenUsageModelBilling$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TokenUsageModelBilling' from JSON`,
  );
}
