/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Usage = {
  /**
   * Number of tokens in the input
   */
  inputTokens: number;
  /**
   * Number of tokens in the output
   */
  outputTokens: number;
  /**
   * Total number of tokens used
   */
  totalTokens: number;
};

/** @internal */
export const Usage$inboundSchema: z.ZodType<Usage, z.ZodTypeDef, unknown> = z
  .object({
    input_tokens: z.number().int(),
    output_tokens: z.number().int(),
    total_tokens: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "input_tokens": "inputTokens",
      "output_tokens": "outputTokens",
      "total_tokens": "totalTokens",
    });
  });

export function usageFromJSON(
  jsonString: string,
): SafeParseResult<Usage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Usage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Usage' from JSON`,
  );
}
