/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Breakdown of input tokens by type
 */
export type InputTokensDetails = {
  /**
   * Number of image tokens in the input
   */
  imageTokens?: number | undefined;
  /**
   * Number of SVG tokens in the input
   */
  svgTokens?: number | undefined;
  /**
   * Number of text tokens in the input
   */
  textTokens?: number | undefined;
};

/**
 * Breakdown of output tokens by type
 */
export type OutputTokensDetails = {
  /**
   * Number of SVG tokens in the output
   */
  svgTokens?: number | undefined;
};

export type Usage = {
  /**
   * Number of tokens in the input
   */
  inputTokens: number;
  /**
   * Breakdown of input tokens by type
   */
  inputTokensDetails?: InputTokensDetails | undefined;
  /**
   * Number of tokens in the output
   */
  outputTokens: number;
  /**
   * Breakdown of output tokens by type
   */
  outputTokensDetails?: OutputTokensDetails | undefined;
  /**
   * Total number of tokens used
   */
  totalTokens: number;
};

/** @internal */
export const InputTokensDetails$inboundSchema: z.ZodType<
  InputTokensDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  image_tokens: z.number().int().optional(),
  svg_tokens: z.number().int().optional(),
  text_tokens: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "image_tokens": "imageTokens",
    "svg_tokens": "svgTokens",
    "text_tokens": "textTokens",
  });
});

export function inputTokensDetailsFromJSON(
  jsonString: string,
): SafeParseResult<InputTokensDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputTokensDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputTokensDetails' from JSON`,
  );
}

/** @internal */
export const OutputTokensDetails$inboundSchema: z.ZodType<
  OutputTokensDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  svg_tokens: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "svg_tokens": "svgTokens",
  });
});

export function outputTokensDetailsFromJSON(
  jsonString: string,
): SafeParseResult<OutputTokensDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OutputTokensDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OutputTokensDetails' from JSON`,
  );
}

/** @internal */
export const Usage$inboundSchema: z.ZodType<Usage, z.ZodTypeDef, unknown> = z
  .object({
    input_tokens: z.number().int(),
    input_tokens_details: z.lazy(() => InputTokensDetails$inboundSchema)
      .optional(),
    output_tokens: z.number().int(),
    output_tokens_details: z.lazy(() => OutputTokensDetails$inboundSchema)
      .optional(),
    total_tokens: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "input_tokens": "inputTokens",
      "input_tokens_details": "inputTokensDetails",
      "output_tokens": "outputTokens",
      "output_tokens_details": "outputTokensDetails",
      "total_tokens": "totalTokens",
    });
  });

export function usageFromJSON(
  jsonString: string,
): SafeParseResult<Usage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Usage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Usage' from JSON`,
  );
}
