/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import {
  SVGParams,
  SVGParams$Outbound,
  SVGParams$outboundSchema,
} from "./svgparams.js";
import {
  SVGVectorizeInput,
  SVGVectorizeInput$Outbound,
  SVGVectorizeInput$outboundSchema,
} from "./svgvectorizeinput.js";

export type VectorizeSVGRequest = {
  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on
   *
   * @remarks
   * their existing frequency in the text so far, decreasing the model's
   * likelihood to repeat the same line verbatim.
   */
  frequencyPenalty?: number | null | undefined;
  /**
   * Input configuration for image-to-SVG vectorization
   */
  input: SVGVectorizeInput;
  /**
   * Maximum tokens in the output
   */
  maxOutputTokens?: number | undefined;
  /**
   * The model to use for generation/editing
   */
  model: string;
  /**
   * Number of SVGs to generate
   */
  n?: number | undefined;
  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on
   *
   * @remarks
   * whether they appear in the text so far, increasing the model's likelihood
   * to talk about new topics.
   */
  presencePenalty?: number | null | undefined;
  /**
   * This feature is in Beta.
   *
   * @remarks
   * If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.
   * Determinism is not guaranteed.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  seed?: number | null | undefined;
  /**
   * If true, the image is analyzed for vectorizability. Images deemed
   *
   * @remarks
   * unsuitable (e.g., photos with complex textures) are automatically
   * simplified before vectorization to improve results.
   */
  simplifyIfNeeded?: boolean | undefined;
  /**
   * If true, responses are streamed as Server-Sent Events
   */
  stream?: boolean | undefined;
  /**
   * SVG-specific generation parameters for controlling canvas, design, and styling.
   *
   * @remarks
   * These parameters give fine-grained control over the generated SVG output.
   */
  svgParams?: SVGParams | undefined;
  /**
   * Sampling temperature
   */
  temperature?: number | undefined;
  /**
   * Nucleus sampling parameter
   */
  topP?: number | undefined;
};

/** @internal */
export type VectorizeSVGRequest$Outbound = {
  frequency_penalty: number | null;
  input: SVGVectorizeInput$Outbound;
  max_output_tokens?: number | undefined;
  model: string;
  n: number;
  presence_penalty: number | null;
  seed?: number | null | undefined;
  simplify_if_needed: boolean;
  stream: boolean;
  svg_params?: SVGParams$Outbound | undefined;
  temperature: number;
  top_p: number;
};

/** @internal */
export const VectorizeSVGRequest$outboundSchema: z.ZodType<
  VectorizeSVGRequest$Outbound,
  z.ZodTypeDef,
  VectorizeSVGRequest
> = z.object({
  frequencyPenalty: z.nullable(z.number().default(0)),
  input: SVGVectorizeInput$outboundSchema,
  maxOutputTokens: z.number().int().optional(),
  model: z.string(),
  n: z.number().int().default(1),
  presencePenalty: z.nullable(z.number().default(0)),
  seed: z.nullable(z.number().int()).optional(),
  simplifyIfNeeded: z.boolean().default(false),
  stream: z.boolean().default(false),
  svgParams: SVGParams$outboundSchema.optional(),
  temperature: z.number().default(1),
  topP: z.number().default(1),
}).transform((v) => {
  return remap$(v, {
    frequencyPenalty: "frequency_penalty",
    maxOutputTokens: "max_output_tokens",
    presencePenalty: "presence_penalty",
    simplifyIfNeeded: "simplify_if_needed",
    svgParams: "svg_params",
    topP: "top_p",
  });
});

export function vectorizeSVGRequestToJSON(
  vectorizeSVGRequest: VectorizeSVGRequest,
): string {
  return JSON.stringify(
    VectorizeSVGRequest$outboundSchema.parse(vectorizeSVGRequest),
  );
}
