/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  ImageInputReference,
  ImageInputReference$Outbound,
  ImageInputReference$outboundSchema,
} from "./imageinputreference.js";

/**
 * Request to check if an image is suitable for vectorization
 */
export type VectorizabilityCheckRequest = {
  /**
   * Reference image input (URL or base64-encoded)
   */
  image: ImageInputReference;
};

/** @internal */
export type VectorizabilityCheckRequest$Outbound = {
  image: ImageInputReference$Outbound;
};

/** @internal */
export const VectorizabilityCheckRequest$outboundSchema: z.ZodType<
  VectorizabilityCheckRequest$Outbound,
  z.ZodTypeDef,
  VectorizabilityCheckRequest
> = z.object({
  image: ImageInputReference$outboundSchema,
});

export function vectorizabilityCheckRequestToJSON(
  vectorizabilityCheckRequest: VectorizabilityCheckRequest,
): string {
  return JSON.stringify(
    VectorizabilityCheckRequest$outboundSchema.parse(
      vectorizabilityCheckRequest,
    ),
  );
}
