/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Result of vectorizability check
 */
export type VectorizabilityCheckResponse = {
  /**
   * Whether the image is suitable for vectorization
   */
  vectorizable: boolean;
};

/** @internal */
export const VectorizabilityCheckResponse$inboundSchema: z.ZodType<
  VectorizabilityCheckResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  vectorizable: z.boolean(),
});

export function vectorizabilityCheckResponseFromJSON(
  jsonString: string,
): SafeParseResult<VectorizabilityCheckResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VectorizabilityCheckResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VectorizabilityCheckResponse' from JSON`,
  );
}
