/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  InputReference,
  InputReference$Outbound,
  InputReference$outboundSchema,
} from "./inputreference.js";

/**
 * Request to check if an image is suitable for vectorization
 */
export type VectorizabilityCheckRequest = {
  image: InputReference;
};

/** @internal */
export type VectorizabilityCheckRequest$Outbound = {
  image: InputReference$Outbound;
};

/** @internal */
export const VectorizabilityCheckRequest$outboundSchema: z.ZodType<
  VectorizabilityCheckRequest$Outbound,
  z.ZodTypeDef,
  VectorizabilityCheckRequest
> = z.object({
  image: InputReference$outboundSchema,
});

export function vectorizabilityCheckRequestToJSON(
  vectorizabilityCheckRequest: VectorizabilityCheckRequest,
): string {
  return JSON.stringify(
    VectorizabilityCheckRequest$outboundSchema.parse(
      vectorizabilityCheckRequest,
    ),
  );
}
