/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * ViewBox dimensions for the SVG coordinate system
 */
export type ViewBox = {
  /**
   * ViewBox height
   */
  height?: number | undefined;
  /**
   * ViewBox width
   */
  width?: number | undefined;
};

/** @internal */
export type ViewBox$Outbound = {
  height: number;
  width: number;
};

/** @internal */
export const ViewBox$outboundSchema: z.ZodType<
  ViewBox$Outbound,
  z.ZodTypeDef,
  ViewBox
> = z.object({
  height: z.number().int().default(24),
  width: z.number().int().default(24),
});

export function viewBoxToJSON(viewBox: ViewBox): string {
  return JSON.stringify(ViewBox$outboundSchema.parse(viewBox));
}
