/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { EventStream } from "../../../lib/event-streams.js";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type AnimateSVGRequest = {
  animateSVGRequest: shared.AnimateSVGRequest;
  /**
   * Optional client-supplied trace identifier. The API echoes this value in `X-Trace-ID` and includes it in request logs for client-side correlation.
   */
  xTraceId?: string | undefined;
};

export type Data = shared.AnimatedSvgResponse;

/**
 * Token totals for token-priced models. Fixed-credit models use `credits` for billing and may report compatibility zeros here.
 */
export type Usage = {
  /**
   * Measured token count for token-priced models. Fixed-credit models retain this field for compatibility and may report zero.
   */
  inputTokens: number;
  /**
   * Measured token count for token-priced models. Fixed-credit models retain this field for compatibility and may report zero.
   */
  outputTokens: number;
  /**
   * Measured token count for token-priced models. Fixed-credit models retain this field for compatibility and may report zero.
   */
  totalTokens: number;
};

/**
 * When `stream` is false, returns `application/json` with the full animated SVG response. When `stream` is true, returns `text/event-stream` with Server-Sent Events. Each SSE message contains an `event:` line (`generating`, `reasoning`, `draft`, or `content`) and a `data:` line with a JSON payload. Token-priced models report measured totals in `usage` and omit `credits`. Fixed-credit models retain compatibility token totals of `0` and report `credits`; for streaming, fixed credits are emitted on completed `content` events. The stream terminates with `data: [DONE]`.
 */
export type AnimateSVGResponseBody = {
  created: number;
  /**
   * Credit cost for fixed-credit models. Omitted for token-priced models, whose measured totals are returned in `usage`.
   */
  credits?: number | undefined;
  data: Array<shared.AnimatedSvgResponse>;
  id: string;
  svgScore?: number | null | undefined;
  usage?: Usage | null | undefined;
};

export type AnimateSVGResponseResult =
  | shared.PublicErrorEnvelope
  | AnimateSVGResponseBody
  | EventStream<shared.SvgStreamEvent>;

export type AnimateSVGResponse = {
  headers: { [k: string]: Array<string> };
  result:
    | shared.PublicErrorEnvelope
    | AnimateSVGResponseBody
    | EventStream<shared.SvgStreamEvent>;
};

/** @internal */
export type AnimateSVGRequest$Outbound = {
  AnimateSVGRequest: shared.AnimateSVGRequest$Outbound;
  "x-trace-id"?: string | undefined;
};

/** @internal */
export const AnimateSVGRequest$outboundSchema: z.ZodType<
  AnimateSVGRequest$Outbound,
  z.ZodTypeDef,
  AnimateSVGRequest
> = z.object({
  animateSVGRequest: shared.AnimateSVGRequest$outboundSchema,
  xTraceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    animateSVGRequest: "AnimateSVGRequest",
    xTraceId: "x-trace-id",
  });
});

export function animateSVGRequestToJSON(
  animateSVGRequest: AnimateSVGRequest,
): string {
  return JSON.stringify(
    AnimateSVGRequest$outboundSchema.parse(animateSVGRequest),
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> =
  shared.AnimatedSvgResponse$inboundSchema;

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const Usage$inboundSchema: z.ZodType<Usage, z.ZodTypeDef, unknown> = z
  .object({
    input_tokens: z.number().int(),
    output_tokens: z.number().int(),
    total_tokens: z.number().int(),
  }).transform((v) => {
    return remap$(v, {
      "input_tokens": "inputTokens",
      "output_tokens": "outputTokens",
      "total_tokens": "totalTokens",
    });
  });

export function usageFromJSON(
  jsonString: string,
): SafeParseResult<Usage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Usage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Usage' from JSON`,
  );
}

/** @internal */
export const AnimateSVGResponseBody$inboundSchema: z.ZodType<
  AnimateSVGResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  created: z.number().int(),
  credits: z.number().int().optional(),
  data: z.array(shared.AnimatedSvgResponse$inboundSchema),
  id: z.string(),
  svg_score: z.nullable(z.number()).optional(),
  usage: z.nullable(z.lazy(() => Usage$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "svg_score": "svgScore",
  });
});

export function animateSVGResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AnimateSVGResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnimateSVGResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnimateSVGResponseBody' from JSON`,
  );
}

/** @internal */
export const AnimateSVGResponseResult$inboundSchema: z.ZodType<
  AnimateSVGResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.PublicErrorEnvelope$inboundSchema,
  z.lazy(() => AnimateSVGResponseBody$inboundSchema),
  z.instanceof(ReadableStream<Uint8Array>)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true, value: undefined };
        return {
          done: false,
          value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent),
        };
      });
    }),
]);

export function animateSVGResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<AnimateSVGResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnimateSVGResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnimateSVGResponseResult' from JSON`,
  );
}

/** @internal */
export const AnimateSVGResponse$inboundSchema: z.ZodType<
  AnimateSVGResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    shared.PublicErrorEnvelope$inboundSchema,
    z.lazy(() => AnimateSVGResponseBody$inboundSchema),
    z.instanceof(ReadableStream<Uint8Array>)
      .transform(stream => {
        return new EventStream(stream, rawEvent => {
          if (rawEvent.data === "[DONE]") {
            return { done: true, value: undefined };
          }
          return {
            done: false,
            value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent),
          };
        });
      }),
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function animateSVGResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnimateSVGResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnimateSVGResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnimateSVGResponse' from JSON`,
  );
}
