/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CheckVectorizabilityResponse =
  | shared.ErrorT
  | shared.VectorizabilityCheckResponse;

/** @internal */
export const CheckVectorizabilityResponse$inboundSchema: z.ZodType<
  CheckVectorizabilityResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.ErrorT$inboundSchema,
  shared.VectorizabilityCheckResponse$inboundSchema,
]);

export function checkVectorizabilityResponseFromJSON(
  jsonString: string,
): SafeParseResult<CheckVectorizabilityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckVectorizabilityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckVectorizabilityResponse' from JSON`,
  );
}
