/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { EventStream } from "../../../lib/event-streams.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CreateSVGVectorizationResponse =
  | shared.SVGResponse
  | shared.ErrorT
  | EventStream<shared.SVGStreamEvent>;

/** @internal */
export const CreateSVGVectorizationResponse$inboundSchema: z.ZodType<
  CreateSVGVectorizationResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.SVGResponse$inboundSchema,
  shared.ErrorT$inboundSchema,
  z.instanceof(ReadableStream<Uint8Array>)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true };
        return { value: shared.SVGStreamEvent$inboundSchema.parse(rawEvent) };
      });
    }),
]);

export function createSVGVectorizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSVGVectorizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSVGVectorizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSVGVectorizationResponse' from JSON`,
  );
}
