/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { EventStream } from "../../../lib/event-streams.js";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type EditSVGRequest = {
  editSVGRequest: shared.EditSVGRequest;
  /**
   * Optional client-supplied trace identifier. The API echoes this value in `X-Trace-ID` and includes it in request logs for client-side correlation.
   */
  xTraceId?: string | undefined;
};

export type EditSVGResponseResult =
  | shared.PublicErrorEnvelope
  | shared.SvgResponse
  | EventStream<shared.SvgStreamEvent>;

export type EditSVGResponse = {
  headers: { [k: string]: Array<string> };
  result:
    | shared.PublicErrorEnvelope
    | shared.SvgResponse
    | EventStream<shared.SvgStreamEvent>;
};

/** @internal */
export type EditSVGRequest$Outbound = {
  EditSVGRequest: shared.EditSVGRequest$Outbound;
  "x-trace-id"?: string | undefined;
};

/** @internal */
export const EditSVGRequest$outboundSchema: z.ZodType<
  EditSVGRequest$Outbound,
  z.ZodTypeDef,
  EditSVGRequest
> = z.object({
  editSVGRequest: shared.EditSVGRequest$outboundSchema,
  xTraceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    editSVGRequest: "EditSVGRequest",
    xTraceId: "x-trace-id",
  });
});

export function editSVGRequestToJSON(editSVGRequest: EditSVGRequest): string {
  return JSON.stringify(EditSVGRequest$outboundSchema.parse(editSVGRequest));
}

/** @internal */
export const EditSVGResponseResult$inboundSchema: z.ZodType<
  EditSVGResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.PublicErrorEnvelope$inboundSchema,
  shared.SvgResponse$inboundSchema,
  z.instanceof(ReadableStream<Uint8Array>)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true, value: undefined };
        return {
          done: false,
          value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent),
        };
      });
    }),
]);

export function editSVGResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<EditSVGResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditSVGResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditSVGResponseResult' from JSON`,
  );
}

/** @internal */
export const EditSVGResponse$inboundSchema: z.ZodType<
  EditSVGResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    shared.PublicErrorEnvelope$inboundSchema,
    shared.SvgResponse$inboundSchema,
    z.instanceof(ReadableStream<Uint8Array>)
      .transform(stream => {
        return new EventStream(stream, rawEvent => {
          if (rawEvent.data === "[DONE]") {
            return { done: true, value: undefined };
          }
          return {
            done: false,
            value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent),
          };
        });
      }),
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function editSVGResponseFromJSON(
  jsonString: string,
): SafeParseResult<EditSVGResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditSVGResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditSVGResponse' from JSON`,
  );
}
