/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { EventStream } from "../../../lib/event-streams.js";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GenerateSVGResponseResult =
  | shared.PublicErrorEnvelope
  | shared.SvgResponse
  | EventStream<shared.SvgStreamEvent>;

export type GenerateSVGResponse = {
  headers: { [k: string]: Array<string> };
  result:
    | shared.PublicErrorEnvelope
    | shared.SvgResponse
    | EventStream<shared.SvgStreamEvent>;
};

/** @internal */
export const GenerateSVGResponseResult$inboundSchema: z.ZodType<
  GenerateSVGResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.PublicErrorEnvelope$inboundSchema,
  shared.SvgResponse$inboundSchema,
  z.instanceof(ReadableStream<Uint8Array>)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        return {
          done: false,
          value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent),
        };
      });
    }),
]);

export function generateSVGResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GenerateSVGResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateSVGResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateSVGResponseResult' from JSON`,
  );
}

/** @internal */
export const GenerateSVGResponse$inboundSchema: z.ZodType<
  GenerateSVGResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    shared.PublicErrorEnvelope$inboundSchema,
    shared.SvgResponse$inboundSchema,
    z.instanceof(ReadableStream<Uint8Array>)
      .transform(stream => {
        return new EventStream(stream, rawEvent => {
          return {
            done: false,
            value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent),
          };
        });
      }),
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function generateSVGResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenerateSVGResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateSVGResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateSVGResponse' from JSON`,
  );
}
