/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GenerateSVGResponse =
  | shared.PublicErrorEnvelope
  | shared.SvgResponse
  | string;

/** @internal */
export const GenerateSVGResponse$inboundSchema: z.ZodType<
  GenerateSVGResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.PublicErrorEnvelope$inboundSchema,
  shared.SvgResponse$inboundSchema,
  z.string(),
]);

export function generateSVGResponseFromJSON(
  jsonString: string,
): SafeParseResult<GenerateSVGResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GenerateSVGResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GenerateSVGResponse' from JSON`,
  );
}
