/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetModelRequest = {
  /**
   * Model identifier
   */
  model: string;
};

export type GetModelResponse = shared.Model | shared.PublicErrorEnvelope;

/** @internal */
export type GetModelRequest$Outbound = {
  model: string;
};

/** @internal */
export const GetModelRequest$outboundSchema: z.ZodType<
  GetModelRequest$Outbound,
  z.ZodTypeDef,
  GetModelRequest
> = z.object({
  model: z.string(),
});

export function getModelRequestToJSON(
  getModelRequest: GetModelRequest,
): string {
  return JSON.stringify(GetModelRequest$outboundSchema.parse(getModelRequest));
}

/** @internal */
export const GetModelResponse$inboundSchema: z.ZodType<
  GetModelResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.Model$inboundSchema,
  shared.PublicErrorEnvelope$inboundSchema,
]);

export function getModelResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetModelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetModelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetModelResponse' from JSON`,
  );
}
