/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetModelRequest = {
  /**
   * Model identifier
   */
  model: string;
};

export type GetModelResponseResult = shared.Model | shared.PublicErrorEnvelope;

export type GetModelResponse = {
  headers: { [k: string]: Array<string> };
  result: shared.Model | shared.PublicErrorEnvelope;
};

/** @internal */
export type GetModelRequest$Outbound = {
  model: string;
};

/** @internal */
export const GetModelRequest$outboundSchema: z.ZodType<
  GetModelRequest$Outbound,
  z.ZodTypeDef,
  GetModelRequest
> = z.object({
  model: z.string(),
});

export function getModelRequestToJSON(
  getModelRequest: GetModelRequest,
): string {
  return JSON.stringify(GetModelRequest$outboundSchema.parse(getModelRequest));
}

/** @internal */
export const GetModelResponseResult$inboundSchema: z.ZodType<
  GetModelResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.Model$inboundSchema,
  shared.PublicErrorEnvelope$inboundSchema,
]);

export function getModelResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetModelResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetModelResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetModelResponseResult' from JSON`,
  );
}

/** @internal */
export const GetModelResponse$inboundSchema: z.ZodType<
  GetModelResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    shared.Model$inboundSchema,
    shared.PublicErrorEnvelope$inboundSchema,
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getModelResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetModelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetModelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetModelResponse' from JSON`,
  );
}
