/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export const ObjectT = {
  OrganizationBalance: "organization.balance",
} as const;
export type ObjectT = ClosedEnum<typeof ObjectT>;

/**
 * Spendable organization credit balance
 */
export type GetOrganizationBalanceResponseBody = {
  availableCredits: number;
  object: ObjectT;
  observedAt: number;
  organizationId: string;
};

export type GetOrganizationBalanceResponseResult =
  | shared.PublicErrorEnvelope
  | GetOrganizationBalanceResponseBody;

export type GetOrganizationBalanceResponse = {
  headers: { [k: string]: Array<string> };
  result: shared.PublicErrorEnvelope | GetOrganizationBalanceResponseBody;
};

/** @internal */
export const ObjectT$inboundSchema: z.ZodNativeEnum<typeof ObjectT> = z
  .nativeEnum(ObjectT);

/** @internal */
export const GetOrganizationBalanceResponseBody$inboundSchema: z.ZodType<
  GetOrganizationBalanceResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  available_credits: z.number(),
  object: ObjectT$inboundSchema,
  observed_at: z.number().int(),
  organization_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "available_credits": "availableCredits",
    "observed_at": "observedAt",
    "organization_id": "organizationId",
  });
});

export function getOrganizationBalanceResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationBalanceResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetOrganizationBalanceResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationBalanceResponseBody' from JSON`,
  );
}

/** @internal */
export const GetOrganizationBalanceResponseResult$inboundSchema: z.ZodType<
  GetOrganizationBalanceResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.PublicErrorEnvelope$inboundSchema,
  z.lazy(() => GetOrganizationBalanceResponseBody$inboundSchema),
]);

export function getOrganizationBalanceResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationBalanceResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetOrganizationBalanceResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationBalanceResponseResult' from JSON`,
  );
}

/** @internal */
export const GetOrganizationBalanceResponse$inboundSchema: z.ZodType<
  GetOrganizationBalanceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    shared.PublicErrorEnvelope$inboundSchema,
    z.lazy(() => GetOrganizationBalanceResponseBody$inboundSchema),
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function getOrganizationBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOrganizationBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOrganizationBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOrganizationBalanceResponse' from JSON`,
  );
}
