/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ListModelsResponse = shared.ErrorT | shared.ListModelsResponse;

/** @internal */
export const ListModelsResponse$inboundSchema: z.ZodType<
  ListModelsResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.ErrorT$inboundSchema,
  shared.ListModelsResponse$inboundSchema,
]);

export function listModelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListModelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListModelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListModelsResponse' from JSON`,
  );
}
