/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type RetrieveModelRequest = {
  /**
   * The ID of the model to retrieve
   */
  model: shared.ModelIdsShared;
};

export type RetrieveModelResponse = shared.ErrorT | shared.Model;

/** @internal */
export type RetrieveModelRequest$Outbound = {
  model: string;
};

/** @internal */
export const RetrieveModelRequest$outboundSchema: z.ZodType<
  RetrieveModelRequest$Outbound,
  z.ZodTypeDef,
  RetrieveModelRequest
> = z.object({
  model: shared.ModelIdsShared$outboundSchema,
});

export function retrieveModelRequestToJSON(
  retrieveModelRequest: RetrieveModelRequest,
): string {
  return JSON.stringify(
    RetrieveModelRequest$outboundSchema.parse(retrieveModelRequest),
  );
}

/** @internal */
export const RetrieveModelResponse$inboundSchema: z.ZodType<
  RetrieveModelResponse,
  z.ZodTypeDef,
  unknown
> = z.union([shared.ErrorT$inboundSchema, shared.Model$inboundSchema]);

export function retrieveModelResponseFromJSON(
  jsonString: string,
): SafeParseResult<RetrieveModelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RetrieveModelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RetrieveModelResponse' from JSON`,
  );
}
