/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { EventStream } from "../../../lib/event-streams.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type VectorizeSVGResponse =
  | shared.PublicErrorEnvelope
  | shared.SvgResponse
  | EventStream<shared.SvgStreamEvent>;

/** @internal */
export const VectorizeSVGResponse$inboundSchema: z.ZodType<
  VectorizeSVGResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.PublicErrorEnvelope$inboundSchema,
  shared.SvgResponse$inboundSchema,
  z.instanceof(ReadableStream<Uint8Array>)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        return { value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent) };
      });
    }),
]);

export function vectorizeSVGResponseFromJSON(
  jsonString: string,
): SafeParseResult<VectorizeSVGResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VectorizeSVGResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VectorizeSVGResponse' from JSON`,
  );
}
