/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { EventStream } from "../../../lib/event-streams.js";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type VectorizeSVGRequest = {
  vectorizeSVGRequest: shared.VectorizeSVGRequest;
  /**
   * Optional client-supplied trace identifier. The API echoes this value in `X-Trace-ID` and includes it in request logs for client-side correlation.
   */
  xTraceId?: string | undefined;
};

export type VectorizeSVGResponseResult =
  | shared.PublicErrorEnvelope
  | shared.SvgResponse
  | EventStream<shared.SvgStreamEvent>;

export type VectorizeSVGResponse = {
  headers: { [k: string]: Array<string> };
  result:
    | shared.PublicErrorEnvelope
    | shared.SvgResponse
    | EventStream<shared.SvgStreamEvent>;
};

/** @internal */
export type VectorizeSVGRequest$Outbound = {
  VectorizeSVGRequest: shared.VectorizeSVGRequest$Outbound;
  "x-trace-id"?: string | undefined;
};

/** @internal */
export const VectorizeSVGRequest$outboundSchema: z.ZodType<
  VectorizeSVGRequest$Outbound,
  z.ZodTypeDef,
  VectorizeSVGRequest
> = z.object({
  vectorizeSVGRequest: shared.VectorizeSVGRequest$outboundSchema,
  xTraceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    vectorizeSVGRequest: "VectorizeSVGRequest",
    xTraceId: "x-trace-id",
  });
});

export function vectorizeSVGRequestToJSON(
  vectorizeSVGRequest: VectorizeSVGRequest,
): string {
  return JSON.stringify(
    VectorizeSVGRequest$outboundSchema.parse(vectorizeSVGRequest),
  );
}

/** @internal */
export const VectorizeSVGResponseResult$inboundSchema: z.ZodType<
  VectorizeSVGResponseResult,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.PublicErrorEnvelope$inboundSchema,
  shared.SvgResponse$inboundSchema,
  z.instanceof(ReadableStream<Uint8Array>)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        if (rawEvent.data === "[DONE]") return { done: true, value: undefined };
        return {
          done: false,
          value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent),
        };
      });
    }),
]);

export function vectorizeSVGResponseResultFromJSON(
  jsonString: string,
): SafeParseResult<VectorizeSVGResponseResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VectorizeSVGResponseResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VectorizeSVGResponseResult' from JSON`,
  );
}

/** @internal */
export const VectorizeSVGResponse$inboundSchema: z.ZodType<
  VectorizeSVGResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.union([
    shared.PublicErrorEnvelope$inboundSchema,
    shared.SvgResponse$inboundSchema,
    z.instanceof(ReadableStream<Uint8Array>)
      .transform(stream => {
        return new EventStream(stream, rawEvent => {
          if (rawEvent.data === "[DONE]") {
            return { done: true, value: undefined };
          }
          return {
            done: false,
            value: shared.SvgStreamEvent$inboundSchema.parse(rawEvent),
          };
        });
      }),
  ]),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function vectorizeSVGResponseFromJSON(
  jsonString: string,
): SafeParseResult<VectorizeSVGResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VectorizeSVGResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VectorizeSVGResponse' from JSON`,
  );
}
