/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  AnimateSVGAcceptEnum,
  animateSVGAnimateSVG,
} from "../funcs/animateSVGAnimateSVG.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export { AnimateSVGAcceptEnum } from "../funcs/animateSVGAnimateSVG.js";

export class AnimateSVG extends ClientSDK {
  /**
   * SVG animation
   *
   * @remarks
   * Animates an input SVG from a remote or base64-encoded SVG source.
   */
  async animateSVG(
    request: operations.AnimateSVGRequest,
    options?: RequestOptions & { acceptHeaderOverride?: AnimateSVGAcceptEnum },
  ): Promise<operations.AnimateSVGResponse> {
    return unwrapAsync(animateSVGAnimateSVG(
      this,
      request,
      options,
    ));
  }
}
