/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  createSVGsGenerateSVG,
  GenerateSVGAcceptEnum,
} from "../funcs/createSVGsGenerateSVG.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export { GenerateSVGAcceptEnum } from "../funcs/createSVGsGenerateSVG.js";

export class CreateSVGs extends ClientSDK {
  /**
   * Text to SVG
   *
   * @remarks
   * Generates one or more SVGs from a prompt and optional references.
   */
  async generateSVG(
    request: operations.GenerateSVGRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GenerateSVGAcceptEnum },
  ): Promise<operations.GenerateSVGResponse> {
    return unwrapAsync(createSVGsGenerateSVG(
      this,
      request,
      options,
    ));
  }
}
