/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  createSVGsGenerateIcon,
  GenerateIconAcceptEnum,
} from "../funcs/createSVGsGenerateIcon.js";
import {
  createSVGsGenerateSVG,
  GenerateSVGAcceptEnum,
} from "../funcs/createSVGsGenerateSVG.js";
import {
  createSVGsVectorizeSVG,
  VectorizeSVGAcceptEnum,
} from "../funcs/createSVGsVectorizeSVG.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export { GenerateIconAcceptEnum } from "../funcs/createSVGsGenerateIcon.js";

export { GenerateSVGAcceptEnum } from "../funcs/createSVGsGenerateSVG.js";

export { VectorizeSVGAcceptEnum } from "../funcs/createSVGsVectorizeSVG.js";

export class CreateSVGs extends ClientSDK {
  /**
   * Generate Icons
   *
   * @remarks
   * Generates one or more icons based on a text prompt.
   * Icons are always generated with a 1:1 aspect ratio and optimized
   * for use at various scales.
   *
   * **NOTE: This endpoint is currently not implemented.**
   *
   * Supports streaming for real-time progressive rendering.
   */
  async generateIcon(
    request: shared.GenerateIconRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: GenerateIconAcceptEnum;
    },
  ): Promise<operations.GenerateIconResponse> {
    return unwrapAsync(createSVGsGenerateIcon(
      this,
      request,
      options,
    ));
  }

  /**
   * Text to SVG
   *
   * @remarks
   * Generates one or more SVG graphics based on a text prompt and optional
   * reference images. Supports streaming for real-time progressive rendering.
   *
   * When `stream` is set to `true`, the response will be sent as Server-Sent
   * Events (SSE) with partial SVG updates followed by a final completion event.
   */
  async generateSVG(
    request: shared.GenerateSVGRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GenerateSVGAcceptEnum },
  ): Promise<operations.GenerateSVGResponse> {
    return unwrapAsync(createSVGsGenerateSVG(
      this,
      request,
      options,
    ));
  }

  /**
   * Image to SVG
   *
   * @remarks
   * Converts a raster image (PNG, JPEG, WebP) into an SVG graphic.
   * Requires exactly one input image. Supports streaming for real-time
   * progressive rendering.
   *
   * When `stream` is set to `true`, the response uses a two-phase streaming model:
   *
   * 1. **Draft phase** (`draft` events): Raw SVG chunks are streamed
   *    in real-time as the model generates them. These provide immediate visual
   *    feedback but may not be fully optimized.
   *
   * 2. **Content phase** (`content` event): After the draft is complete,
   *    a refined and optimized SVG is sent as the final result with usage statistics.
   */
  async vectorizeSVG(
    request: shared.VectorizeSVGRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: VectorizeSVGAcceptEnum;
    },
  ): Promise<operations.VectorizeSVGResponse> {
    return unwrapAsync(createSVGsVectorizeSVG(
      this,
      request,
      options,
    ));
  }
}
