/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { EditSVGAcceptEnum, editSVGEditSVG } from "../funcs/editSVGEditSVG.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export { EditSVGAcceptEnum } from "../funcs/editSVGEditSVG.js";

export class EditSVG extends ClientSDK {
  /**
   * SVG edit
   *
   * @remarks
   * Edits an input SVG from inline SVG markup or a remote/base64 SVG source.
   */
  async editSVG(
    request: operations.EditSVGRequest,
    options?: RequestOptions & { acceptHeaderOverride?: EditSVGAcceptEnum },
  ): Promise<operations.EditSVGResponse> {
    return unwrapAsync(editSVGEditSVG(
      this,
      request,
      options,
    ));
  }
}
