/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsGetModel } from "../funcs/modelsGetModel.js";
import { modelsListModels } from "../funcs/modelsListModels.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Models extends ClientSDK {
  /**
   * Get Model
   *
   * @remarks
   * Returns metadata for a single model.
   */
  async getModel(
    request: operations.GetModelRequest,
    options?: RequestOptions,
  ): Promise<operations.GetModelResponse> {
    return unwrapAsync(modelsGetModel(
      this,
      request,
      options,
    ));
  }

  /**
   * List Models
   *
   * @remarks
   * Returns all models available to the authenticated organization.
   */
  async listModels(
    options?: RequestOptions,
  ): Promise<operations.ListModelsResponse> {
    return unwrapAsync(modelsListModels(
      this,
      options,
    ));
  }
}
