/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { modelsListModels } from "../funcs/modelsListModels.js";
import { modelsRetrieveModel } from "../funcs/modelsRetrieveModel.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Models extends ClientSDK {
  /**
   * List models
   *
   * @remarks
   * Lists the currently available Arrow models, providing detailed information
   * about each one including capabilities, pricing, and supported features.
   */
  async listModels(
    options?: RequestOptions,
  ): Promise<shared.ListModelsResponse> {
    return unwrapAsync(modelsListModels(
      this,
      options,
    ));
  }

  /**
   * Retrieve model
   *
   * @remarks
   * Retrieves a model instance, providing detailed information about the model
   * including capabilities, pricing, and supported features.
   *
   * This endpoint is compatible with the OpenAI SDK.
   */
  async retrieveModel(
    request: operations.RetrieveModelRequest,
    options?: RequestOptions,
  ): Promise<operations.RetrieveModelResponse> {
    return unwrapAsync(modelsRetrieveModel(
      this,
      request,
      options,
    ));
  }
}
