/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  AnimateSVGAcceptEnum,
  modifySVGsAnimateSVG,
} from "../funcs/modifySVGsAnimateSVG.js";
import {
  EditSVGAcceptEnum,
  modifySVGsEditSVG,
} from "../funcs/modifySVGsEditSVG.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export { AnimateSVGAcceptEnum } from "../funcs/modifySVGsAnimateSVG.js";

export { EditSVGAcceptEnum } from "../funcs/modifySVGsEditSVG.js";

export class ModifySVGs extends ClientSDK {
  /**
   * Animate SVGs
   *
   * @remarks
   * Adds CSS animations to an existing SVG graphic based on a motion prompt.
   * The source SVG can be provided as an inline string or URL.
   * Supports streaming for real-time progressive rendering.
   *
   * **NOTE: This endpoint is currently not implemented.**
   *
   * When `stream` is set to `true`, the response will be sent as Server-Sent
   * Events (SSE) with partial SVG updates followed by a final completion event.
   */
  async animateSVG(
    request: shared.AnimateSVGRequest,
    options?: RequestOptions & { acceptHeaderOverride?: AnimateSVGAcceptEnum },
  ): Promise<operations.AnimateSVGResponse> {
    return unwrapAsync(modifySVGsAnimateSVG(
      this,
      request,
      options,
    ));
  }

  /**
   * Edit SVGs
   *
   * @remarks
   * Edits an existing SVG graphic based on a text prompt and optional
   * reference images. The source SVG can be provided as an inline string
   * or URL. Supports streaming for real-time progressive rendering.
   *
   * **NOTE: This endpoint is currently not implemented.**
   *
   * When `stream` is set to `true`, the response will be sent as Server-Sent
   * Events (SSE) with partial SVG updates followed by a final completion event.
   */
  async editSVG(
    request: shared.EditSVGRequest,
    options?: RequestOptions & { acceptHeaderOverride?: EditSVGAcceptEnum },
  ): Promise<operations.EditSVGResponse> {
    return unwrapAsync(modifySVGsEditSVG(
      this,
      request,
      options,
    ));
  }
}
