/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationGetOrganizationBalance } from "../funcs/organizationGetOrganizationBalance.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import { unwrapAsync } from "./types/fp.js";

export class Organization extends ClientSDK {
  /**
   * Get Organization Balance
   *
   * @remarks
   * Requires an admin API key with billing_read or * authority. Returns the authenticated organization's spendable credits across all projects. Pending reservations, expired funding, and refunds are excluded. The balance is a JSON number with up to three fractional digits; very large balances may lose floating-point precision. This is a snapshot and may change after the response. The organization's request-rate limit applies and may return 429.
   */
  async getOrganizationBalance(
    options?: RequestOptions,
  ): Promise<operations.GetOrganizationBalanceResponse> {
    return unwrapAsync(organizationGetOrganizationBalance(
      this,
      options,
    ));
  }
}
