/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Models } from "./models.js";
import { Svg } from "./svg.js";

export class QuiverAI extends ClientSDK {
  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _svg?: Svg;
  get svg(): Svg {
    return (this._svg ??= new Svg(this._options));
  }
}
