/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { CreateSVGs } from "./createsvgs.js";
import { Models } from "./models.js";

export class QuiverAI extends ClientSDK {
  private _models?: Models;
  get models(): Models {
    return (this._models ??= new Models(this._options));
  }

  private _createSVGs?: CreateSVGs;
  get createSVGs(): CreateSVGs {
    return (this._createSVGs ??= new CreateSVGs(this._options));
  }
}
