/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { svgCheckVectorizability } from "../funcs/svgCheckVectorizability.js";
import {
  CreateSVGAnimationAcceptEnum,
  svgCreateSVGAnimation,
} from "../funcs/svgCreateSVGAnimation.js";
import {
  CreateSVGCollectionAcceptEnum,
  svgCreateSVGCollection,
} from "../funcs/svgCreateSVGCollection.js";
import {
  CreateSVGEditAcceptEnum,
  svgCreateSVGEdit,
} from "../funcs/svgCreateSVGEdit.js";
import {
  CreateSVGGenerationAcceptEnum,
  svgCreateSVGGeneration,
} from "../funcs/svgCreateSVGGeneration.js";
import {
  CreateSVGVectorizationAcceptEnum,
  svgCreateSVGVectorization,
} from "../funcs/svgCreateSVGVectorization.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export { CreateSVGAnimationAcceptEnum } from "../funcs/svgCreateSVGAnimation.js";

export { CreateSVGCollectionAcceptEnum } from "../funcs/svgCreateSVGCollection.js";

export { CreateSVGEditAcceptEnum } from "../funcs/svgCreateSVGEdit.js";

export { CreateSVGGenerationAcceptEnum } from "../funcs/svgCreateSVGGeneration.js";

export { CreateSVGVectorizationAcceptEnum } from "../funcs/svgCreateSVGVectorization.js";

export class Svg extends ClientSDK {
  /**
   * Check image vectorizability
   *
   * @remarks
   * Analyzes an image and returns whether it is suitable for vectorization.
   * Use this for pre-flight validation before calling the vectorize endpoint.
   */
  async checkVectorizability(
    request: shared.VectorizabilityCheckRequest,
    options?: RequestOptions,
  ): Promise<operations.CheckVectorizabilityResponse> {
    return unwrapAsync(svgCheckVectorizability(
      this,
      request,
      options,
    ));
  }

  /**
   * Animate SVGs
   *
   * @remarks
   * Adds CSS animations to an existing SVG graphic based on a motion prompt.
   * The source SVG can be provided as an inline string or URL.
   * Supports streaming for real-time progressive rendering.
   *
   * When `stream` is set to `true`, the response will be sent as Server-Sent
   * Events (SSE) with partial SVG updates followed by a final completion event.
   */
  async createSVGAnimation(
    request: shared.AnimateSVGRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: CreateSVGAnimationAcceptEnum;
    },
  ): Promise<operations.CreateSVGAnimationResponse> {
    return unwrapAsync(svgCreateSVGAnimation(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate SVG collections
   *
   * @remarks
   * Generates an icon set from a single descriptive prompt. The model will
   * interpret the prompt to create multiple coherent, related SVGs.
   *
   * Example prompt: "create an icon set with home, web, computer, and settings icons"
   *
   * Supports streaming for real-time progressive rendering.
   */
  async createSVGCollection(
    request: shared.CollectionSVGRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: CreateSVGCollectionAcceptEnum;
    },
  ): Promise<operations.CreateSVGCollectionResponse> {
    return unwrapAsync(svgCreateSVGCollection(
      this,
      request,
      options,
    ));
  }

  /**
   * Edit SVGs
   *
   * @remarks
   * Edits an existing SVG graphic based on a text prompt and optional
   * reference images. The source SVG can be provided as an inline string
   * or URL. Supports streaming for real-time progressive rendering.
   *
   * When `stream` is set to `true`, the response will be sent as Server-Sent
   * Events (SSE) with partial SVG updates followed by a final completion event.
   */
  async createSVGEdit(
    request: shared.EditSVGRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: CreateSVGEditAcceptEnum;
    },
  ): Promise<operations.CreateSVGEditResponse> {
    return unwrapAsync(svgCreateSVGEdit(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate SVGs
   *
   * @remarks
   * Generates one or more SVG graphics based on a text prompt and optional
   * reference images. Supports streaming for real-time progressive rendering.
   *
   * When `stream` is set to `true`, the response will be sent as Server-Sent
   * Events (SSE) with partial SVG updates followed by a final completion event.
   */
  async createSVGGeneration(
    request: shared.QuiverMessage,
    options?: RequestOptions & {
      acceptHeaderOverride?: CreateSVGGenerationAcceptEnum;
    },
  ): Promise<operations.CreateSVGGenerationResponse> {
    return unwrapAsync(svgCreateSVGGeneration(
      this,
      request,
      options,
    ));
  }

  /**
   * Vectorize image to SVG
   *
   * @remarks
   * Converts a raster image (PNG, JPEG, WebP) into an SVG graphic.
   * Requires exactly one input image. Supports streaming for real-time
   * progressive rendering.
   *
   * When `stream` is set to `true`, the response uses a two-phase streaming model:
   *
   * 1. **Draft phase** (`svg_vectorize.draft` events): Raw SVG chunks are streamed
   *    in real-time as the model generates them. These provide immediate visual
   *    feedback but may not be fully optimized.
   *
   * 2. **Content phase** (`svg_vectorize.content` event): After the draft is complete,
   *    a refined and optimized SVG is sent as the final result with usage statistics.
   */
  async createSVGVectorization(
    request: shared.VectorizeSVGRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: CreateSVGVectorizationAcceptEnum;
    },
  ): Promise<operations.CreateSVGVectorizationResponse> {
    return unwrapAsync(svgCreateSVGVectorization(
      this,
      request,
      options,
    ));
  }
}
