/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { svgUtilitiesCheckSVGVectorizability } from "../funcs/svgUtilitiesCheckSVGVectorizability.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class SVGUtilities extends ClientSDK {
  /**
   * Check image vectorizability
   *
   * @remarks
   * Analyzes an image and returns whether it is suitable for vectorization.
   * Use this for pre-flight validation before calling the vectorize endpoint.
   */
  async checkSVGVectorizability(
    request: shared.VectorizabilityCheckRequest,
    options?: RequestOptions,
  ): Promise<operations.CheckSVGVectorizabilityResponse> {
    return unwrapAsync(svgUtilitiesCheckSVGVectorizability(
      this,
      request,
      options,
    ));
  }
}
