/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  VectorizeSVGAcceptEnum,
  vectorizeSVGVectorizeSVG,
} from "../funcs/vectorizeSVGVectorizeSVG.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export { VectorizeSVGAcceptEnum } from "../funcs/vectorizeSVGVectorizeSVG.js";

export class VectorizeSVG extends ClientSDK {
  /**
   * Image to SVG
   *
   * @remarks
   * Converts an image input into an SVG output.
   */
  async vectorizeSVG(
    request: shared.VectorizeSVGRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: VectorizeSVGAcceptEnum;
    },
  ): Promise<operations.VectorizeSVGResponse> {
    return unwrapAsync(vectorizeSVGVectorizeSVG(
      this,
      request,
      options,
    ));
  }
}
