/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @quiverai/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx modelsGetModel.example.ts
 */

import { QuiverAI } from "@quiverai/sdk";

const quiverAI = new QuiverAI({
  bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await quiverAI.models.getModel({
    model: "arrow-0.5",
  });

  console.log(result);
}

main().catch(console.error);
